### ISSUE TITLE
Add subscription support using MQTT over Websockets.

### ISSUE THREAD

**Issue by PedroAlvarado** [awslabs/aws-mobile-appsync-sdk-android#1]
It looks this client doesn't support subscriptions via MQTT over Websockets. It'd be great to have this feature available in the Android client.

**Comment by rohandubal** [comment]
Hello @PedroAlvarado ,

Thanks for submitting this feature request. I will keep this thread updated on when we add this feature.

Thanks,
Rohan

**Comment by minbi** [comment]
Hi @PedroAlvarado,

We have just released version 2.6.16 with subscriptions. Please check it out and let us know your thoughts!
