### ISSUE TITLE
Is there a way to clear the mutation queue?

### ISSUE THREAD

**Issue by gitnarqt** [awslabs/aws-mobile-appsync-sdk-android#101]
**Take this scenario:**
User authenticates with Cognito, perform mutations offline, logs out. A new user logs in, connects to the internet, mutations performed by the first user are executed.

Is there a way to clear the mutationQueue or cancel all non-executed mutations?

**Environment:**
 - AppSync SDK Version: 2.7.1

**Comment by cbommas** [comment]
@gitnarqt 

There is currently no mechanism to clear the mutationQueue or to cancel all non-executed mutations. Each mutation, however, is cancelable and you can cancel outstanding mutations if you were to be tracking them within the app.

I am going to take this as a feature request and post back once here when I have more information or a timeline that I can share.

**Comment by cbommas** [comment]
@gitnarqt 
v2.7.6 contains the mechanism to clear the mutation queue. See the link below for an example of how to use this.

https://github.com/awslabs/aws-mobile-appsync-sdk-android/blob/1dd1fd9959837438896bd4aa39f8de5c426a23b7/aws-android-sdk-appsync-tests/src/androidTest/java/com/amazonaws/mobileconnectors/appsync/AWSAppSyncQueryInstrumentationTest.java#L1198

**Comment by gitnarqt** [comment]
@cbommas awesome! Worked like a charm, thank you for the prompt update.

**Comment by cbommas** [comment]
@gitnarqt 
Thank you for confirming!
