### ISSUE TITLE
Mutations on background thread

### ISSUE THREAD

**Issue by matthewlip** [awslabs/aws-mobile-appsync-sdk-android#104]
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/80, when I want to run a mutation; I have to start it from the UI thread

**Describe the solution you'd like**
I'd like to be able to start mutations from a background thread

**Additional context**
Using appsync version 2.6.26

**Comment by cbommas** [comment]
@matthewlip 

The latest version of the AppSync SDK, v2.7.5, enables you to start mutations from a background thread. See the following for an example https://github.com/awslabs/aws-mobile-appsync-sdk-android/blob/757d8e08ed3576d296e1a6eec972a94b013751b5/aws-android-sdk-appsync-tests/src/androidTest/java/com/amazonaws/mobileconnectors/appsync/AWSAppSyncConflictManagementInstrumentationTest.java#L309

**Comment by matthewlip** [comment]
One version bump later and everything is working as expected; thank you for your time.
