### ISSUE TITLE
[AWSMobileClient] Cannot resolve symbol `Callback`

### ISSUE THREAD

**Issue by JagritiHirwani** [awslabs/aws-mobile-appsync-sdk-android#110]
I am following the link given https://aws-amplify.github.io/docs/android/authentication and when i am building the project i get the following error :C:\Users\Lenovo\AndroidStudioProjects\MyApplication5\app\src\main\java\com\example\lenovo\myapplication\MainActivity.java:42: error: cannot find symbol
        AWSMobileClient.getInstance().initialize(getApplicationContext(), new Callback<UserStateDetails>() {
                                                                              ^
  symbol:   class Callback
  location: class MainActivity

**Comment by sunchunqiang** [comment]
Hi @JagritiHirwani 

Did you add implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.11.+' to your build.gradle?

**Comment by kvasukib** [comment]
@JagritiHirwani Sorry for the inconvenience caused. `Callback` was introduced in a recent version of `aws-android-sdk-mobile-client` library. I would check your build.gradle for the version of the library and upgrade to `com.amazonaws:aws-android-sdk-mobile-client:2.11.+` as @sunchunqiang pointed out.

**Comment by JagritiHirwani** [comment]
@sunchunqiang yes i did add it.
these are the dependencies in my build gradle.
 //Base SDK
    implementation 'com.amazonaws:aws-android-sdk-core:2.11.+'
    //AppSync SDK
    implementation 'com.amazonaws:aws-android-sdk-appsync:2.7.+'
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
    **implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.11.+'**

//For the drop-in UI also:
    implementation 'com.amazonaws:aws-android-sdk-auth-userpools:2.11.+'
    implementation 'com.amazonaws:aws-android-sdk-auth-ui:2.11.+'

**Comment by minbi** [comment]
Hi @JagritiHirwani ,

Your setup looks to be correct. The gradle settings may be out of sync with your project.

If you are only missing the `Callback` symbol, can you check whether you java imports in the file include this line?
```
import com.amazonaws.mobile.client.Callback;
```
