### ISSUE TITLE
Memory leak when subscription is cancelled

### ISSUE THREAD

**Issue by mitmak777** [awslabs/aws-mobile-appsync-sdk-android#111]
**Describe the bug**
subscriptionsById still holds the subscription instance after it is cancelled and unsubscribed.

I believe the cause is this line
https://github.com/awslabs/aws-mobile-appsync-sdk-android/blob/55717d1c074065ee1b004af65c38201bb20c8eb9/aws-android-sdk-appsync/src/main/java/com/amazonaws/mobileconnectors/appsync/subscription/RealSubscriptionManager.java#L106

 It try to remove the instance by key but the value is passed to the remove function

**Comment by cbommas** [comment]
@mitmak777 
Nice catch! Thank you. This will be fixed in one of our upcoming releases. We will post back on this thread once the release is out.

**Comment by mitmak777** [comment]
Thanks for the quick response.

**Comment by cbommas** [comment]
@mitmak777 

The latest version of the sdk (v2.7.7) contains the fix. Please upgrade and let us know how it goes.

**Comment by cbommas** [comment]
@mitmak777 
Closing this issue as you may be all set. Please feel free to post here if this issue is still happening .
