### ISSUE TITLE
First letter in field name changed to lower case

### ISSUE THREAD

**Issue by EunGyeongChoe** [awslabs/aws-mobile-appsync-sdk-android#115]
**Describe the bug**
https://github.com/apollographql/apollo-android/issues/994

If a field name starts with a capital letter then Apollo changes it to a lower case letter. This causes the query or mutation to fail. Changing the function and variable names is just fine, but the marshaller should use a non-modified field name.

---

A bug has not been fixed in "aws-mobile-appsync-sdk-android" 

한국어)
"apollo-android" 에서는 해당 버그가 수정되었으나, "aws-mobile-appsync-sdk-android" 에서는
버그가 남아있습니다.
InputFieldMarshaller 에서 필드명의 첫글자를 소문자로 바꿔버립니다.

**Comment by rohandubal** [comment]
@minbi could you please have a look at this issue?

**Comment by devxpy** [comment]
Wow, this issue single-handedly managed to take down an entire app
