### ISSUE TITLE
Best way to perform schema migration?

### ISSUE THREAD

**Issue by gitnarqt** [awslabs/aws-mobile-appsync-sdk-android#116]
**Question**
Is there a recommended way to perform a schema migration?

**The scenario we're facing:**
- The user performs some operations while offline
- App gets updated on Google Playstore with a new schema
- The user gets back into the app while still offline, attempts to load old data with a new schema
- App crashes

**Alternatives we thought of:**
- Force user to connect to the internet and wait for mutationQueue to empty
- Perform a migration on the AWS backend
- Download the migrated data
The issue with the above approach is that if one mutation fails, it can never be recovered.

**Another alternative:**
- Have multiple schemas locally 
- Load, Migrate and Mutate data locally

**A Third alternative:**
- Make all fields nullable in the schema
- We only add fields to the schema (So we don't delete or modify any field name)
- Handle missing fields (null) on the Android client side

**Comment by kvasukib** [comment]
@gitnarqt Sorry for the inconvenience caused. Can you post a stacktrace and the two schemas?

**Comment by cbommas** [comment]
@gitnarqt 
I would like to setup a call to discuss this with you along with others on my team.
Would you be open to it? If so, send me your contact info ( my handle is chabom at amazon.com) and I'll get a call organized.

**Comment by gitnarqt** [comment]
@cbommas thank you for that, we would love to jump on a call and discuss this further. Just sent an email

**Comment by Joseph82** [comment]
@cbommas @gitnarqt is there any development?

**Comment by muellerfr** [comment]
Hi @awsed, can you take a look at this issue?

**Comment by gitnarqt** [comment]
We're facing a small issue with the Third alternative mentioned above that is:

- Make all fields nullable in the schema
- We only add fields to the schema (So we don't delete or modify any field name)
- Handle missing fields (null) on the Android client side

The issue with this approach is if an object was created without the added fields, and then the user updated his app with the new schema that includes the added fields, loading the data created using the old schema from local storage will throw a NullPointerException caused by Missing Field.

We could copy the auto-generated files and place them in a separate folder then modify them in such a way to handle the exception when reading that missing field. When the exception is caught, we substitute the result of that field with null instead of an exception.

Any other suggestions on how to solve this? Would you recommend another strategy?

**Comment by awsed** [comment]
Deprecating fields with the @deprecated annotation is the recommended way. Then you can use the new CloudWatch log insights integration to track field usage (https://aws.amazon.com/blogs/mobile/getting-more-visibility-into-graphql-performance-with-aws-appsync-logs/) and finally remove it when you detect there's no invocation to the deprecated fields. That way you guarantee old clients won't be affected, new capabilities can be added via new types and new fields on those types without creating a breaking change.

It looks like you had non-nullable/mandatory fields in a give type at some stage then removed those fields with a change to the GraphQL schema in AppSync, is that correct? It's not very clear to me the types of queries that are returning an error after you implemented the deprecation. Are you able to provide an example?

**Comment by Joseph82** [comment]
@gitnarqt we are facing a similar dilemma. And also thought the best idea was to add nullable fields (and never remove old fields). However we find out that data saved locally with old schema cannot be read with the new schema.

Imagine an item, stored in the local data store with the record:

{"__typename":"Todo",
"id":"4AAB0D63-1AA3-411D-86F5-0AA226D35369",
"name":"Fix mutation",
"createDateTime":"2019-05-02T16:06:26+02:00"}

Now suppose we add in the schema a nullable field, let's call it `version`. The new created Todo items will look like:

{"__typename":"Todo",
"id":"4AAB0D63-1AA3-411D-86F5-0AA226D35369",
"name":"Fix mutation",
"createDateTime":"2019-05-02T16:06:26+02:00",
 "version":"1"}

Now, this one would be ok, but when trying to read the first one we get an error, I guess it is because in the query that new field is defined, but cannot be found. This below are the fields we ask in the query. 

todo {
            id, name, version, createDateTime
        }

How did you mange @gitnarqt to allow the new query to read old data?

**Comment by gitnarqt** [comment]
Sorry for the late reply guys.

@awsed thank you for the suggestion! I guess @Joseph82 explained the issue with a detailed example, thank you for that!

@Joseph82 we went through the AppSync code and found out that there is a method called `fieldValue(Record record, ResponseField field)` that throws a NullPointerException with a message `"Missing value: " + field.fieldName()`. We forked the repository and made it return null instead of throwing a NullPointerException. You can find the commit here: https://github.com/gitnarqt/aws-mobile-appsync-sdk-android/commit/7327f82030747ad348c7ddcc585dcfc71d75dcd9

Please feel free to use the fork we created. So far it's working perfectly but I really hope anyone from the AppSync team could modify that in their source code to make it accessible to everyone.

**Comment by Joseph82** [comment]
Hi @gitnarqt thank you for replying. 

We also thought about changing the source code, but I think a better option would be to include the change into the main repository. Did you try to make a PR?

**Comment by gitnarqt** [comment]
@Joseph82 you're most welcome! Just performed one: https://github.com/awslabs/aws-mobile-appsync-sdk-android/pull/199

**Comment by Joseph82** [comment]
Nice :) Thank you @gitnarqt

**Comment by gitnarqt** [comment]
@kvasukib I made a PR regarding this fix and not sure if another alternative solution was implemented. Can you please advise?

**Comment by ahardin** [comment]
@awsed can we please get @gitnarqt's PR (#199) merged? I also left a comment in that PR with another solution, but I think his is probably the way to go. 

Thanks!

**Comment by ahardin** [comment]
I hate to nag, but is anyone from AWS seeing this? I now have a ~4 month old version of this repo going through a janky build process to Jitpack just so I can use the patched version. Can we get the @gitnarqt PR pulled?
