### ISSUE TITLE
AppSync ensure all items are receieved from dynamoDB

### ISSUE THREAD

**Issue by devxpy** [awslabs/aws-mobile-appsync-sdk-android#124]
Hey there!

I have around 3K items in my dynamoDB database, and I need to fetch almost all of them.

I wrote a paginator that fetches items in batches of 500 until the `nextToken` is returned as null. 

However, this approach seems to return an inconsistent amount of "total" items.

What's the recommended way to do this?

Using this -> `implementation 'com.amazonaws:aws-android-sdk-appsync:2.7.+@aar'`

**Comment by devxpy** [comment]
@cbommas I'm really sorry. My testing methodology was broken.

The number of items returned is 100% consistent across devices.

**Comment by muellerfr** [comment]
@devxpy - thank you for updating the issue, and happy to hear it's working.
