### ISSUE TITLE
Can I use this SDK with my own GraphQL endpoint?

### ISSUE THREAD

**Issue by mithleshjs** [awslabs/aws-mobile-appsync-sdk-android#125]
I have my own custom back-end with both GraphQL and REST API. I was able to connect my REST API with AppSync using HTTP endpoint. But since AppSync is based on GraphQL, I was wondering if I can use this SDK to directly consume my GraphQL API.

**Comment by cbommas** [comment]
@mithleshjs 
yes, this SDK is intended to be used directly with GraphQL API implemented using AppSync.

**Comment by mithleshjs** [comment]
What I am saying is my GraphQL API is not implemented with AppSync.

**Comment by cbommas** [comment]
@mithleshjs 
Sorry, I misunderstood. Unfortunately, you can't use this SDK with an API that is not implemented in AppSync.

**Comment by mithleshjs** [comment]
@cbommas It also works with API that is not implemented in AppSync.
