### ISSUE TITLE
Apollo mapping not working with Appsync Gradle plugin 2.7.8

### ISSUE THREAD

**Issue by Joseph82** [awslabs/aws-mobile-appsync-sdk-android#127]
We were using appSync gradle plugin, version `2.6.17`. But now we are trying to switch to the latest available `2.7.8`. ('com.amazonaws:aws-android-sdk-appsync-gradle-plugin:2.7.8'). 

The problem is that after the update, the custom adapter we wrote doesn't work anymore. It is a `AWSDateTime<->java.util.Date` defined in the gradle as follow:

```
apollo {
    customTypeMapping = [
            "AWSDateTime": "java.util.Date"
    ]
}
```
Now the generated Java model doesn't have anymore a `java.util.Date` but a `String`.

**Comment by btilbrook-nextfaze** [comment]
Looks related to #77

**Comment by Joseph82** [comment]
Still having the problem. I tried with the latest version:

`com.amazonaws:aws-android-sdk-appsync-gradle-plugin:2.10.0`

but the mapping doesn't work anymore.

**Comment by desokroshan** [comment]
@Joseph82 The PR has not been merged yet. Can you work off of the PR and let me know if that fixes the issue?
Thanks for your patience!

**Comment by Joseph82** [comment]
@desokroshan I checked the PR, but I honestly don't know if that is gonna fix the problem.
Is there any test for that?

**Comment by Joseph82** [comment]
Any news about this? We are still stuck on `2.6.17` plugin.

**Comment by TrekSoft** [comment]
Per the PR, the resolution is that you should define your own custom DateTime type (e.g., ConvertibleDateTime) rather than overriding a core type.
