### ISSUE TITLE
ApolloParseException - Failed to parse http response - java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by rahatshahzeb** [awslabs/aws-mobile-appsync-sdk-android#128]
Getting ApolloParseException while parsing the below schema:

```
query GetUserData($id: Int!) {
  getUserData(id: $id) {
    id
    firstName
    lastName
    username
    email
    phone
    access
    status
  }
}
```

 - AppSync SDK Version: 2.7.8
 - Device: OPPO A71k, Emulator
 - Android Version: Nougat 7.1.1

If I remove the `id` from schema, it works fine. What could be the possible reason?

**Comment by rohandubal** [comment]
Hello @rahatshahzeb 

Sorry that you are having issues using the SDK. Could you please post your schema here so that I can try to reproduce this on my side? 

Thanks,
Rohan

**Comment by okayan** [comment]
@rohandubal I had occurred the same problem. (ApolloParseException)
Probably Int type **id**  is a factor.
If I remove the id from the schema, it works fine, too.

**Comment by desokroshan** [comment]
@rahatshahzeb @okayan Can you please share the stacktrace and schema so that I can try to reproduce on my end?

**Comment by okayan** [comment]
@rahatshahzeb I corrected the hierarchy and then I got no errors.
So I can't share stack trace and schema.

**Comment by desokroshan** [comment]
@rahatshahzeb Is this still an issue for you? It is recommended that `id` be of GraphQL scalar type 'ID'. If you have a use case where you absolutely need to have an `id` of type `Int`, please feel free to share it with us so that we can consider supporting it.
