### ISSUE TITLE
"appsyncstore" database too large

### ISSUE THREAD

**Issue by devxpy** [awslabs/aws-mobile-appsync-sdk-android#131]
So I noticed that my app's storage usage is increasing for no apparent reason over time.

Inspecting further, I saw that the "appsyncstore" database is taking up too much space, and it increases quite rapidly..

```
$ adb shell ls -lRa /data/user/0/online.meghshala.app/databases/

/data/user/0/online.meghshala.app/databases/:
-rw-rw---- u0_a70   u0_a70   90021888 2019-03-14 02:35 appsyncstore
-rw------- u0_a70   u0_a70     524288 2019-03-14 02:35 appsyncstore-journal
-rw-rw---- u0_a70   u0_a70      24576 2019-03-14 01:30 appsyncstore_mutation
-rw------- u0_a70   u0_a70       8720 2019-03-14 01:30 appsyncstore_mutation-journal
```

It seems to occur even when I use `AppSyncResponseFetchers.NETWORK_ONLY`

Even running `appSyncClient.store.clearAll()` won't help.

**Comment by rohandubal** [comment]
Hello @devxpy 

Have you recently noticed this change after upgrading to a different SDK version or is it part of the same app? Has the app been doing more queries and the data being cached? This would explain why the cache size keeps growing for you.

Thanks,
Rohan

**Comment by devxpy** [comment]
Sorry, should have mentioned this.

I've been using these since the first commit -


```gradle
    implementation 'com.amazonaws:aws-android-sdk-core:2.11.+'

    implementation('com.amazonaws:aws-android-sdk-mobile-client:2.11.+@aar') { transitive = true }
    implementation('com.amazonaws:aws-android-sdk-auth-userpools:2.11.+@aar') { transitive = true }

    implementation 'com.amazonaws:aws-android-sdk-s3:2.11.+'

    implementation 'com.amazonaws:aws-android-sdk-appsync:2.7.+@aar'
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'

```

---

The app does sync on every launch. So, I couldn't care much for the cache. I already have that in the form of a couchbase DB.

**Comment by kvasukib** [comment]
@devxpy Sorry for the delayed response. 

`AppSyncResponseFetchers.NETWORK_ONLY` should not store the data in the local cache on the device. Are you sure all of your queries and subscriptions use the `NETWORK_ONLY` fetcher only?

With regards to clearing the cache used for queries, you need to do `appSyncClient.store.clearAll().execute()` in order to clear the local query cache. `appSyncClient.store.clearAll()` only returns a `GraphQLOperation` and you need to call `.execute()` on it in order to perform the operation.

**Comment by kvasukib** [comment]
Closing this issue. Please feel free to re-open if the issue persists even after calling `appSyncClient.store.clearAll().execute()`.
