### ISSUE TITLE
Offline Mutations are failed, when the user is logged out

### ISSUE THREAD

**Issue by JgdshSeerm** [awslabs/aws-mobile-appsync-sdk-android#138]
I have added Offline mutations, then the user is logged out due to inactive. 
Now the user is back with the internet, but there is no accesstoken. and the offline mutations are started to sync. and expectedly it fails due to **401( authorization == null)**.

Help me with any ideas to handle this type of scenaiors.

**Comment by palpatim** [comment]
@JgdshSeerm 

Our expectation is that using CognitoUserPools or AWSMobileClient as your AppSync's auth provider, and you are using `AWS_IAM` or `AMAZON_COGNITO_USER_POOLS` as your auth mode, that the SDK would request a new access token before making a network call--*as long as there is a valid refresh token*.

Can you clarify your use case & configuration for us?

* What SDK version are you using?
* How are you configuring your AppSync client's auth provider?
* What auth mode are you using?
* If you're using UserPools, what is your refresh token's expiration date set to?
