### ISSUE TITLE
Subscriptions to mutations don't work when the device that is subscribed to mutation is offline and comes back online

### ISSUE THREAD

**Issue by yendanghms** [awslabs/aws-mobile-appsync-sdk-android#139]
I am having issue with Amazon AppSync as below:
#### Function awsAppSyncClient.query work fine.
 
I am flowing to Amazon’s document at: https://aws-amplify.github.io/docs/android/start

**Comment by rohandubal** [comment]
Hello @yendanghms 

Could you please provide some more information regarding when you encounter this issue? What schema are you using? Can you paste some sample code?

Best,
Rohan

**Comment by yendanghms** [comment]
Hi @rohandubal ,

1. Here is GraphQL :

```
mutation UpdateCurrency {
updateCurrency(input: {
 id: "586b94b5-697b-4501-abf4-ade852d9b96f"
 exchangeRate: 10000
})
{
 id
 exchangeRate
 name
 symbol
}
}
```
2.  Here is schema.graphql

```
type Subscription {

  onUpdateCurrency(exchangeRate: Float, id: ID, name: String, symbol: String): Currency @aws_subscribe(mutations : ["updateCurrency"])
}
```

3. Kotlin code

- Init AWS

``` Kotlin
val  aws = AWSAppSyncClient.builder()
            .context(applicationContext)
            .awsConfiguration(AWSConfiguration(applicationContext))
            // If you are using complex objects (S3) then uncomment
            //.s3ObjectManager(new S3ObjectManagerImplementation(new AmazonS3Client(AWSMobileClient.getInstance())))
            .build()
```
- Subscription event
``` Kotlin
val subscription = OnUpdateCurrencySubscription.builder().symbol("VND").build()
        val subscriptionWatcher = aws.subscribe(subscription)
        subscriptionWatcher.execute(object : AppSyncSubscriptionCall.Callback<OnUpdateCurrencySubscription.Data> {
            override fun onFailure(e: ApolloException) {
                Timber.d("OnUpdateCurrencySubscription onFailure ${e.message}")
            }

            override fun onResponse(response: Response<OnUpdateCurrencySubscription.Data>) {
                Timber.d("OnUpdateCurrencySubscription onResponse ")
            }

            override fun onCompleted() {
                Timber.d("OnUpdateCurrencySubscription onCompleted ")
            }

        })
```

Thank you!

**Comment by desokroshan** [comment]
@yendanghms Thanks for sharing the schema and code snippet. I will try to reproduce the issue on my end and post my updates here.

**Comment by Sanghati** [comment]
I am facing the same issue, I am subscribe to a mutation while online my subscription is working fine but when I mutate using console and changing my device mode from offline to online the subscription is not working. My device here is android.

**Comment by kvasukib** [comment]
@Sanghati Sorry for the inconvenience caused. Let me re-iterate what you said for accuracy:

1. AWSAppSyncClient subscribed to a mutation.
2. Device A is online, subscriptions work great.
3. Device A is offline.
4. Device B (here AppSync console from your desktop) makes a mutation.
5. Device A comes back online.
6. Subscriptions don't work.

Where are you seeing this exception: "java.net.UnknownHostException: Unable to resolve host No address associated with hostname
detailed Message : failed to execute http call"?

Do you see logs in your app where the device came back online and the SDK received the network online callback?

Do you have the subscriptions active when the device came back online?

**Comment by SwiftyWang** [comment]
Same issue happened.
