### ISSUE TITLE
Executing subscriptions with multiple response types does not work. 

### ISSUE THREAD

**Issue by KasemJaffer** [awslabs/aws-mobile-appsync-sdk-android#14]
It only works when I execute one subscription. More than one subscription leads to unexpected behavior like dropping connection or only one of the running subscription working and the rest not.

**Comment by KasemJaffer** [comment]
Thank you for the quick reply,

I'm using Cognito User Pools Authorization method. Only one subscription is allowed for this type of authorization as well?

**Comment by minbi** [comment]
Thanks for the report, we will try to reproduce this issue

**Comment by sargentin** [comment]
@KasemJaffer, 
No, Cognito User Pools authorization allows multiple subscriptions, as well as IAM.

**Comment by minbi** [comment]
I have tried to reproduce with 2 subscriptions running at the same time and it seems to be ok. How many are you trying to run simultaneously?

Are you using the latest version of the sdk and gradle plugin in? 2.6.19 currently.

**Comment by KasemJaffer** [comment]
Only two subscriptions with different response type. I am using this version com.amazonaws:aws-android-sdk-appsync:2.6.19.  

N.B. I got a different answer from the support team.
Here is the reply

> 
> Thank you for your time on the chat.
> 
> You wanted to know if it was possible to subscribe to multiple different operations with a single subscription. After testing with my own API I can confirm that it is possible, with the caveat that all of the operations you want to subscribe to must have the same return type.
> 
> Using the sample API that is available in the AppSync console as an example, you can create the following subscription types:
> 
> subscribeToNewEvents: Event
>         @aws_subscribe(mutations: ["createEvent"])
> subscribeToDeletedEvents: Event
>         @aws_subscribe(mutations: ["deleteEvent"])
> subscribeToEventComments(eventId: String!): Comment
>         @aws_subscribe(mutations: ["commentOnEvent"])
> 
> You can create a subscription type that will return info about more than one operation like so:
> 
> subscribeToEventChanges: Event
>         @aws_subscribe(mutations: ["createEvent","deleteEvent"])
> 
> This works as both createEvent and deleteEvent have the return type of Event. However it is not possible to create a subscription that will return any type. In the above example we could not create a subscription with ["createEvent", "commentOnEvent"] as this would be two different return types. This is likely due to the return type governing what fields may be returned. You can find some more examples in the docs[1].
> 
> Hopefully this answers your question. Please let me know if you have any follow up questions.
> 
> [1] https://docs.aws.amazon.com/appsync/latest/devguide/real-time-data.html : Real-Time Data
> 
> 
> Best regards,
> Eanna B.
> Amazon Web Services
