### ISSUE TITLE
How to optimistically delete item in uncountable large data set?

### ISSUE THREAD

**Issue by eliasbagley** [awslabs/aws-mobile-appsync-sdk-android#149]
Hey all - 

I'm hoping you can help me out with a use case I'm struggling with. I'm working with the events starter app, and have added a little bit more functionality to prove out using AppSync for a realtime messaging application. I'd like to provide the user the ability to scroll up multiple pages, and delete a single item from the dataset, and have the UI automatically re-render from the state of the cache.
If I fetch for the entire data set, I'm able to achieve this using a query watcher, along with optimistically deleting the item from the cache using the `writeAndPublish` API on store. (An aside - I thought the `refetchQueries` option on a mutation would also handle this, but they don't seem to be working for me. Perhaps a topic for a separate thread though). I'm doing the optimistic delete using the same pattern that the sample apps use:

```java
    private void deleteEventOffline(final ListEventsQuery.Item pendingItem) {
        final AWSAppSyncClient awsAppSyncClient = ClientFactory.getInstance(this);

        final ListEventsQuery listEventsQuery = ListEventsQuery.builder().build();

        awsAppSyncClient.query(listEventsQuery)
                .responseFetcher(AppSyncResponseFetchers.CACHE_ONLY)
                .enqueue(new GraphQLCall.Callback<ListEventsQuery.Data>() {
                    @Override
                    public void onResponse(@Nonnull Response<ListEventsQuery.Data> response) {
                        List<ListEventsQuery.Item> items = new ArrayList<>();
                        if (response.data() != null) {
                            items.addAll(response.data().listEvents().items());
                        }

                        items.remove(pendingItem);
                        ListEventsQuery.Data data = new ListEventsQuery.Data(new ListEventsQuery.ListEvents("EventConnection", items, null));
                        awsAppSyncClient.getStore()
                                .writeAndPublish(listEventsQuery, data)
                                .enqueue(null);
                    }

                    @Override
                    public void onFailure(@Nonnull ApolloException e) {
                        Log.e(TAG, "Failed to update event query list.", e);
                    }
                });
    }

```
This works because I'm updating the same query that my query watcher is observing, so the query watcher re-triggers and updates the UI.

The issue comes along when I attempt to paginate through this data - the pattern above suggests that in order to do an optimistic delete, I need to know which query the delete item would belong to, so that I can remove the item from the result of this query, and resave it. How exactly am I supposed to achieve that? This would require knowing the query that originally fetched the item for each item in the list, which seems like a pain to manually track. Furthermore, even if I were to track this query, would this guarantee that this item also gets removed from the result of other query watchers that may contain this item, or do I need to track every query that might possibly contain my deleted item, so that I can update them all?

I think the ability that I want is to be able to insert or remove a single item from the cache, without having to know which queries currently contain it, and have the UI automatically re-render when the underlying cache changes. Is this possible with the current caching model?

**Environment(please complete the following information):**
 - 2.7.9

**Device Information (please complete the following information):**
 - Pixel 2

**Comment by palpatim** [comment]
@eliasbagley 

There isn't really a good way to delete an object from the associated queries. My suggestion would be to delete the referenced object by its key, then subsequent cached `ListEventsQuery` results would reference a null object, which should cause it to not display.

With that said, we don't currently have tests around this behavior, so it's possible that the Events Starter schema is set up to not allow null results in a list. Alternately, the Apollo layer may object to a query reference that resolves to a null object, so I can't immediately confirm that this will work as I describe.

**Comment by eliasbagley** [comment]
Thanks for the reply @palpatim - I tried your suggestion by doing:

```java
awsAppSyncClient.getStore()
    .remove(CacheKey.from(event.id())
    .execute()
```

I was able to confirm that this does indeed delete the item from the cache as expected, but doesn't cause my UI to optimistically updated like I want, because it causes my QueryWatcher to experience a cache miss. Because my QueryWatcher is `CACHE_ONLY`, I get a null list. I was hoping that the query watcher would return something like: `list = [Event1, Event2, null, Event4, etc]` if I manually remove Event3 from the cache, but instead I get `list = null'. 

I dug into the caching code, and this query is being resolved to a null list because the underlying cache Record for the query that my QueryWatcher is watching looks like:
```
key: listEventsQuery(limit: 10, nextToken: $VALUE), value: [{"__typename":"EventConnection","items":["ApolloCacheReference{$EVENT_ID_1}","ApolloCacheReference{$EVENT_ID_2}","ApolloCacheReference{$EVENT_ID_3}","ApolloCacheReference{$EVENT_ID_4}" ...]
```
Because there is still an `ApolloCacheReference` listed for Event3 in this query, when the resolver tries to resolve this query from the cache, it sees that `ApolloCacheReference{$EVENT_ID_3}` resolves to `null`, which resolves the entire `listEventsQuery(limit: 10, nextToken: $VALUE)` query to null, instead of just resolving `null` for the missing event 3.

It doesn't seem to be an issue with the schema, since the GraphQL schema does allow null items in the list:

```
type EventConnection {
	items: [Event]
	nextToken: String
}
```

This seems to be a design decision of the Apollo cache, where it only is a cache hit if it can resolve everything the query is referencing.

I don't know if there is a way to customize this cache resolving behavior, or if there is another approach you might suggest in order for me to delete an item from a paged data set without keeping track of all the queries myself. Any suggestions?

**Comment by palpatim** [comment]
Unfortunately the cache design doesn't really incorporate the idea of "membership" in a way that makes it easy to find operations that reference individual model objects. Short of maintaining a list yourself (that is, a map of objects to operation keys in which those objects are referenced), I'm not sure what else could be done.

This seems like it would be a good feature request as we consider AppSync's behavior with locally cached data, so if you'd like to open a feature request (or convert this issue to a feature request for future consideration) please feel free and we'll add it to our backlog.
