### ISSUE TITLE
Support for writeQuery and readQuery

### ISSUE THREAD

**Issue by jakebonk** [awslabs/aws-mobile-appsync-sdk-android#15]
I noticed that ReactJS has support for writeQuery and readQuery and was wondering how far along this feature is for Android?

Thanks

**Comment by minbi** [comment]
Can you elaborate what are the features you expect with writeQuery and readQuery?

The cache store is available through AWSAppSyncClient#getStore()

**Comment by jakebonk** [comment]
Will this be able to update queries that were cached? Also is there any documentation you could link on using getStore?

**Comment by jakebonk** [comment]
I was able to figure it out, using getStore() I was able to update the cached items!
