### ISSUE TITLE
Cannot resolve symbol 'CreateTodoInput'

### ISSUE THREAD

**Issue by palpatim** [awslabs/aws-mobile-appsync-sdk-android#152]
Originally opened by [JanHorcicka](https://forums.aws.amazon.com/profile.jspa?userID=481169) on [AWS Forums](https://forums.aws.amazon.com/thread.jspa?threadID=301751&tstart=0)

---

I am following Android SDK guide step by step. https://aws-amplify.github.io/docs/android/start?ref=amplify-android-btnEverything is running smoothly until I get to the Step 5. I cannot continue because Android Studio finds errors in the provided code. Everything that has to do with CreateTodoInput is red underlined with Android Studio saying Cannot resolve symbol 'CreateTodoInput'.I searched on the web as much as possible and only answers are connected to syncing the Gradle. Which I did, multiple times in many different ways. But this unfortunately doesn't help and I still see this error.See screenshot of the Android Studio: https://ibb.co/kJ7Ky0QCan you please tell me how to get rid of this error?

**Comment by JanHorcicka** [comment]
Hello Roshan,

do you have any update on this?

Thanks,

Jan

**Comment by desokroshan** [comment]
@JanHorcicka The screenshot link is broken. Can you please upload it again?

**Comment by JanHorcicka** [comment]
Here it is: https://ibb.co/znt7wjC

**Comment by desokroshan** [comment]
This issue has been resolved in an offline discussion. The issue here was with an instruction step in the doc which was not very explicit. I have created a [PR](https://github.com/aws-amplify/docs/pull/649/files) for document update(referenced above).

**Comment by Aishabibi21** [comment]
@JanHorcicka @desokroshan @palpatim 
Please can you help me. I have the same problem. I looked through the whole answers on internet.
![image](https://user-images.githubusercontent.com/53967244/62821233-b6b55800-bb26-11e9-95d7-b9da3247db3d.png)

I have those files inside my graphql file as well. I don`t know where is the error
![image](https://user-images.githubusercontent.com/53967244/62821244-d5b3ea00-bb26-11e9-8f1f-4adb6874736a.png)

**Comment by JanHorcicka** [comment]
Did you run the last "amplify push" command? That was the problem in my case.

**Comment by swaroop23** [comment]
Hey I have the same issue. And I have tried a lot of solutions, nothing is working for me. Can anyone help me out?
![errormessageTodo](https://user-images.githubusercontent.com/30334961/64903573-4aa3b200-d6d9-11e9-845b-6b16c36ce29d.JPG)

**Comment by Mzuraiqi** [comment]
@Aishabibi21 @swaroop23 

Hey guys. Before using queries, the mutations and their inputs, please make sure that your query is already generated, otherwise Android studio will not be able to resolve the names.

To verify that go to java(generated) folder in your app and make sure that your query/mutation java class is listed there:
![image](https://user-images.githubusercontent.com/63443992/83109706-88f7ca80-a0ca-11ea-99ea-d3fd83315ba8.png)

 If not, that means that your schema was not complied and pushed well.
