### ISSUE TITLE
Subscribe not receive All messages

### ISSUE THREAD

**Issue by habahbehbassam** [awslabs/aws-mobile-appsync-sdk-android#154]
**Chat App**

**Which AWS Services are you utilizing?**
 'com.amazonaws:aws-android-sdk-core:2.13.2'
 'com.amazonaws:aws-android-sdk-appsync:2.7.8'
 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.1'
 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'

**Provide code snippets (if applicable)**

1. Added Permissions and MqttService to manifests 
```
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_CONTACTS" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

`<service android:name="org.eclipse.paho.android.service.MqttService" />`

2. Create AppSync Client 

```
syncClient = AWSAppSyncClient.builder()
                .context(context)
                .cognitoUserPoolsAuthProvider(() -> token.get())
                .awsConfiguration(new AWSConfiguration(context))
                .subscriptionsAutoReconnect(true)
                .build();

```
3. Create Subscription Call
```
SubscribeByUserIdSubscription subscribe = SubscribeByUserIdSubscription.builder()
                .receiver_user_id(receiverUserId)
                .build();
tAppSyncSubscriptionCall = syncClient.subscribe( subscribe  );

```
4. Call Subscription and wait new Messages 

```

tAppSyncSubscriptionCall.execute(subscriptionCallBack);

private AppSyncSubscriptionCall.Callback<T> subscriptionCallBack= new AppSyncSubscriptionCall.Callback<T>() {
        @Override
        public void onResponse(@Nonnull Response<T> response) {
            handleGraphQlSuccessResponse(null, response);
        }

        @Override
        public void onFailure(@Nonnull ApolloException e) {
            handleGraphQlFailureResponse(null, e);
        }

        @Override
        public void onCompleted() {
            handleOnCompleted();
        }
    };
```
**which type of network you are using when experiencing this issues ?**
WIFI , 4G

**Are you using parametrized subscriptions ?**
Yes, set user ID for subscribe , to get all messages related for this user . 

**Do you mean that sometimes when you subscribe you don't receive any message on that session, or just a few of the messages get lost?** 
 Just a few of the messages get lost.

**Is the Android App in the foreground when you experience this issue, or in the background?**
Foreground 

**Is it possible that Android is killing the Service that is running this subscription?**
No.

**Device Information (please complete the following information):**
 - Device: [Samsung S9 , Samsung S7, Huawei trt-L21A]
 - Android Version: [7.0 , 8.0.0 , 9]

**Comment by habahbehbassam** [comment]
@desokroshan any feedback about my issue ?

**Comment by habahbehbassam** [comment]
I think this issue occurs because the subscribe  disconnected after 5 second from connected , and some message lose when reconnect .

How Can increase this 5 second or find any solution for this issue?
 
Check network monitor image please
![subscribe_network_monitor](https://user-images.githubusercontent.com/17256991/57296442-b0ea4980-70d5-11e9-882a-7919e33e38f3.png)

**Comment by palpatim** [comment]
@habahbehbassam Please see my note on #178--I'm not aware of anything that would force a disconnect of a properly-established connection after 5 seconds. Are you able to provide a small project, or a fork of the events starter, that replicates the problem you're seeing?

**Comment by habahbehbassam** [comment]
@palpatim Please give me your email, I will send sample project for you.

**Comment by habahbehbassam** [comment]
@palpatim I have checked Event App and my code looks the same , but the problem still exists .
I sent a sample project to this email palpatim@palpatim.com , Because I don't want to expose my schema.

**Comment by starer93** [comment]
I got the same issue, in my case, it's less than 5 seconds, it is constantly adding new subscription object and close old connection.

wondering if this has anything to do with the backend settings

**Comment by linxu1231** [comment]
I got the same issue. IOS is just work fine which calling the same subscription.

**Comment by starer93** [comment]
I got it working. 
if you use :  compile 'com.amazonaws:aws-android-sdk-appsync:2.8.+'
however, if you following the [doc](https://aws-amplify.github.io/docs/android/api) ,using implementation 'com.amazonaws:aws-android-sdk-appsync:2.9.+', then this issue occurs.

**Comment by habahbehbassam** [comment]
> I got it working. you should use : compile 'com.amazonaws:aws-android-sdk-appsync:2.8.+'
> 
> however, if you following the [doc](https://aws-amplify.github.io/docs/android/api) ,using implementation 'com.amazonaws:aws-android-sdk-appsync:2.9.+', then this issue occurs.

@starer93  I try it but still lose some messages , are you sure your subscribe receive all messages ? 
if yes , please send for me sample of your code for My mail ( habahbehbassam@gmail.com ).

Thanks ;

**Comment by umarF** [comment]
Similar issue, cant get any subscription event triggered.. but it works on console..
https://stackoverflow.com/questions/56318163/aws-appsync-onupdate-subscription-not-working-on-simulator

**Comment by habahbehbassam** [comment]
We fixed this issue via replace MQTT version from 1.2.1 to 1.2.0 .
Now we use AppSync with version 2.9.0 and MQTT version is 1.2.0 , and it's work.

**Comment by linxu1231** [comment]
> We fixed this issue via replace MQTT version from 1.2.1 to 1.2.0 .
> Now we use AppSync with version 2.9.0 and MQTT version is 1.2.0 , and it's work.
That also worked for me.
Thank you.
