### ISSUE TITLE
java.lang.IllegalStateException: Stack is empty 

### ISSUE THREAD

**Issue by alanvan0502** [awslabs/aws-mobile-appsync-sdk-android#156]
**Describe the bug**

We experienced the above bug. Seems like AppSync cannot parse null data. This bug has been reported and fixed on Apollo side (refer to this link: https://github.com/apollographql/apollo-android/issues/542)

**Expected behavior**
AppSync should be able to handle null response. Please review.

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.7.9

**Comment by andrepiper** [comment]
Open since May 2019. Any updates project is in final stages and dont know what to do. Thanks.
