### ISSUE TITLE
'compile' instead of 'implementation' complaint when building project

### ISSUE THREAD

**Issue by dy08** [awslabs/aws-mobile-appsync-sdk-android#17]
Hi I am seeing a message like following when I build my project using aws-mobile-appsync-sdk-android

Configuration  'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. 

This happens due to build.gradle file in aws-mobile-appsync-sdk-android

Is there a plan to replace 'compile' keyword with 'implementation' or 'api' keyword soon?

**Comment by minbi** [comment]
Hi @dy08 ,

The Gradle plugin for releasing the SDK does not support the new `implementation` and `api` keywords, so they are still using the `compile` keyword to generate dependencies. We will migrate to the new keywords when the Gradle plugin is ready.

To be clear, this question is directed at the source code in the repo and not a symptom of using the `aws-android-sdk-appsync` or `aws-android-sdk-appsync-gradle-plugin` correct?

**Comment by dy08** [comment]
Unfortunately this happens when I use **android-sdk-appsync (using gradle)** .
I may have setup the project in a wrong way, but please take a look at this issue.

#### dependencies for compile configuration

$ ./gradlew :app:dependencies --configuration compile

> Configure project :app 
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Task :app:dependencies 

------------------------------------------------------------
Project :app
------------------------------------------------------------

compile - Compile dependencies for 'main' sources (deprecated: use 'implementation' instead).
\--- com.amazonaws:aws-android-sdk-appsync-runtime:2.6.16
     +--- com.google.code.findbugs:jsr305:3.0.1
     +--- com.squareup.okhttp3:okhttp:3.8.1
     |    \--- com.squareup.okio:okio:1.13.0
     +--- com.nytimes.android:cache:2.0.2
     |    \--- com.google.code.findbugs:jsr305:3.0.1
     \--- com.amazonaws:aws-android-sdk-appsync-api:2.6.16
          +--- com.google.code.findbugs:jsr305:3.0.1
          +--- javax.annotation:jsr250-api:1.0
          \--- com.squareup.okhttp3:okhttp:3.8.1 (*)

(*) - dependencies omitted (listed previously)


BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed

**Comment by dy08** [comment]
Unfortunately this happens when using the android-sdk-appsync with gradle

$ ./gradlew :app:dependencies --configuration compile

> Configure project :app 
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Task :app:dependencies 

------------------------------------------------------------
Project :app
------------------------------------------------------------

compile - Compile dependencies for 'main' sources (deprecated: use 'implementation' instead).
\--- com.amazonaws:aws-android-sdk-appsync-runtime:2.6.16
     +--- com.google.code.findbugs:jsr305:3.0.1
     +--- com.squareup.okhttp3:okhttp:3.8.1
     |    \--- com.squareup.okio:okio:1.13.0
     +--- com.nytimes.android:cache:2.0.2
     |    \--- com.google.code.findbugs:jsr305:3.0.1
     \--- com.amazonaws:aws-android-sdk-appsync-api:2.6.16
          +--- com.google.code.findbugs:jsr305:3.0.1
          +--- javax.annotation:jsr250-api:1.0
          \--- com.squareup.okhttp3:okhttp:3.8.1 (*)

(*) - dependencies omitted (listed previously)

**Comment by minbi** [comment]
Which version of the appsync gradle plugin are you using? If not 2.6.19 can you try that?

**Comment by dy08** [comment]
Sorry for the late reply
I am using 2.6.19 at the moment

**Comment by dy08** [comment]
I'm sorry for the late reply
I was using 2.6.16 for the aws-android-sdk-appsync-gradle-plugin
After updating to 2.6.19, the compile warning disappeared

Thank you very much

**Comment by minbi** [comment]
Closing since version 2.6.19 has fixed the issue.
