### ISSUE TITLE
Is there any reason not to have any validation of current timestamp?

### ISSUE THREAD

**Issue by norio-agoop** [awslabs/aws-mobile-appsync-sdk-android#185]
**State your question**
Hi, I am using AppSync SDK iOS and Android right now. And I have just realized there is no validation of current timestamp on the Android SDK.
For instance, It will be `AWSAppSyncClientError` on the iOS SDK If some user is trying to make some request with changing timestamp either past or future (approximately +- 1~2min) and It won't make any request after that.

**Provide code snippets (if applicable)**

**AWSAppSyncClientError**
https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/64bd6f2afa3aa8569b35000426b06240f52f7132/AWSAppSyncClient/AWSAppSyncClientError.swift#L9

**Environment(please complete the following information):**
 - AppSync SDK Version: [e.g. 2.7.8]

**Device Information (please complete the following information):**
 - Device: Pixel 3
 - Android Version: 9

**Comment by desokroshan** [comment]
@norio-agoop Can you please share the use-case you are targeting. Are you using delta-sync or trying to authenticate your requests? By changing the timestamp, do you mean changing the time on the device that is used to make the requests? For iOS, can you please share the stack trace you see when the request is made with modified timestamp?

**Comment by norio-agoop** [comment]
@desokroshan 
> Can you please share the use-case you are targeting. 

I'd like AppSync SDK to validate the user device's timestamp if the user makes some request with AppySync as the iOS SDK do.

> Are you using delta-sync or trying to authenticate your requests? 

I'm not sure what is delta-sync. I'm using Network-Only. No cache. It just likes the REST API.

> can you please share the stack trace you see when the request is made with modified timestamp?

Okay. Let me share this later. I will upload some screenshots.

**Comment by norio-agoop** [comment]
@desokroshan
I think that this my fault that this validation is no SDK task. I'm going to close this issue. I am currently using AppSync with Cognito and I think it validates the current timestamp.
