### ISSUE TITLE
How do i disable offline mutation?

### ISSUE THREAD

**Issue by atthapon-k** [awslabs/aws-mobile-appsync-sdk-android#189]

**Comment by desokroshan** [comment]
@atthapon-k Just to clarify the mutation are not executed when the device is offline. All the mutations that are issued while the device is offline are queued to be replayed when device comes back online. Do you want your mutations to not be queued at all when its offline? We do not have an API to accomplish that as of now? Could you please elaborate on your use-case?

**Comment by atthapon-k** [comment]
> @atthapon-k Can you please share more details? Based on my initial understanding of your request I would like to clarify that the mutation are not executed when the device is offline. All the mutations that are issued while the device is offline are queued to be replayed when device comes back online. Do you want your mutations to not be queued at all when its offline? We do not have an API to accomplish that as of now. Could you please elaborate on your use-case so that so we can have discussion about adding as a feature if it makes sense.

First of all, thank you for your quick respond.
You understand correctly. l don't want to execute mutation after device back to online that mean my mutation should not be queued while device offline.
Make offline mutation to optional feature, is it possible?

**Comment by svanegas** [comment]
@atthapon-k, did you do something in particular to achieve this? or some resolution you would like to share? I would appreciate it

**Comment by manideepl** [comment]
@desokroshan 
In case you do the mutation offline and want to be notified of the result when the device is online again, how do we do that?
Especially when the app is in the background or when it is killed?
