### ISSUE TITLE
Make GraphQLStoreOperation.Callback public

### ISSUE THREAD

**Issue by cjami** [awslabs/aws-mobile-appsync-sdk-android#192]
From the official docs for an optimistic write we have:

`client.getStore().write(listTodosQuery, data).enqueue(null);`

Currently there is no way to determine the point of success of a `AWSAppSyncClient.getStore().write` operation.

This returns a `GraphQLStoreOperation` on which you **should** be able to enqueue a `GraphQLStoreOperation.Callback` but currently cannot due to this interface not being public.

This is important as it is needed to inform the application of when it can query the cache and correctly receive the created mutation.

**Comment by desokroshan** [comment]
@cjami Thanks for the PR. I will review soon as I can.

**Comment by jamesonwilliams** [comment]
This was fixed [here](https://github.com/awslabs/aws-mobile-appsync-sdk-android/commit/d36dc7c648ac5e336d2a8398cca8b7ab945a528a); the fix is present in 2.10.1 onward.
