### ISSUE TITLE
Possible conflict between queries and mutations

### ISSUE THREAD

**Issue by Joseph82** [awslabs/aws-mobile-appsync-sdk-android#197]
Suppose we have the following scenario (taken from the AppSync documentation)

```
schema {
    query:Query
}

type Query {
    getTodos: [Todo]
}

type Todo {
    id: ID!
    name: String
    description: String
    priority: Int
}
```

Suppose, we also have:
- a create mutation query and
- an update mutation query, that allows changing the `priority` field. 
Also assume that for every mutation we use an optimistic update.

Now, from a clean scenario (empty database remotely and locally), let's assume we follow these steps:
1. ONLINE, we add a Todo item (using the create mutation). The Item will appear in the local db, and in the remote one. The initial priority is 0.
2. OFFLINE, we edit (changing the priority field from 0 to 1) a Todo item (using the update mutation). Now the item will be updated locally (because of the optimistic update), but of course in the remote database nothing will still change. On the other hand a pending mutation will be created.
3. Now we go ONLINE, and as soon as we do this assume there is a trigger that tries to get all remote todos (`getTodos` query). At the same time, the pending mutation will be executed.

My question here is: Is it possible that based on the order of those two events the result changes? For example consider this scenario:
- instant_0 : `getTodos` is executed: this query will get the remote data, which means the old item with priority 0, and this will override also the local database, so the local item will be again the old one (with priority 0)
- instant_1: the optimistic update is triggered and the item in the backend will be modified (priority field will change from 0 to 1)

So this would end up having remotely the correct (new) data and locally the wrong (old) data.

**Comment by Joseph82** [comment]
Does anybody has any idea?

**Comment by Joseph82** [comment]
Is anybody aware of this issue?

**Comment by Joseph82** [comment]
Is there anybody that knows if this is a relevant issue or if the "conflict" cannot occur?

**Comment by gitnarqt** [comment]
@Joseph82 I might be able to help out.

To answer your question, yes this will happen and we faced the exact same issue in the past. To overcome this issue, we prevented the user from doing any query from the server before insuring that the mutation queue is completely empty. This is our version of the issue: https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/107

Hope this helps!

**Comment by Joseph82** [comment]
@gitnarqt thank you for the answer. 

We had to use a similar solution: basically we wait until there are no mutations pending, and then we gather remote data.
