### ISSUE TITLE
Sync method wrong signature?

### ISSUE THREAD

**Issue by mlykotom** [awslabs/aws-mobile-appsync-sdk-android#198]
We use appsync with `kotlin` and wanted to try the `sync` method, but I was unable due to wrong generic paramaters in the method. I was trying to follow the documentation here, but the real method has signature:

```
public <D extends Query.Data, T, V extends Query.Variables> Cancelable sync(
            @Nonnull Query<D, T, V> baseQuery,
            GraphQLCall.Callback<Query.Data> baseQueryCallback,
            Subscription<D,T,V> subscription,
            AppSyncSubscriptionCall.Callback subscriptionCallback,
            Query<D,T,V> deltaQuery,
            GraphQLCall.Callback<Query.Data> deltaQueryCallback,
            long baseRefreshIntervalInSeconds) {
```
Which means, you have to have `D, T, V` generics the same for base query, subscriptions and delta query. But this is not possible, because you will have different graphql generated classes...

Also another issue is, that the callbacks expect `GraphQLCall.Callback<Query.Data>` which means, you cannot have callback with your data, but must have the base one.

**Comment by palpatim** [comment]
@mlykotom 

We don't yet officially support Kotlin, but if you're aware of an annotation or structure in the Java code that would cause the Kotlin signature to be properly generated, please feel free to submit a pull request. Ideally, such a PR would not change the Java API, but I admit I'm not well-versed in Kotlin/Java interoperability, so I'm not clear if such an outcome is achievable.
