### ISSUE TITLE
Add sort options to graphql schema

### ISSUE THREAD

**Issue by Crisp3333** [awslabs/aws-mobile-appsync-sdk-android#200]
**Is your feature request related to a problem? Please describe.**
For cases where a query result is returned they are automatically sorted in ascending order. There should be a clear and concise way of getting a sort in descending order.I moved from direct DynamoDB querying to implementing my app in AppSync only to find out an atomic operation is hard to figure out how to implement. I have looked at other problems associated to this and only get pointed to  "set scanIndexForward" without any proper way of implementing it.  Where should I add this "scanIndexForward"? knowing that graphql/AppSync has encapsulated DynamoDB operations with its own functions and implementations, and without proper knowledge of writing resolvers, it leaves one playing `vtl` roulette with one extra headache of learning a new language. These things cut into production time when you could be focusing on actual code. 

I am aslo aware of the `ModelSortDirection` `enum` type, which I believe does some form of sorting. However, my schema is basic at minimum, that is, I am not creating `@connections`, `@functions` etc. Also this `enum` type is not among my generated Java files.

**Describe the solution you'd like**
Looking at the queries (vtl files (req)) generated by `amplify push, ` the `scanIndexForward` field is left out, which of course will sort your query results in ascending order by default. 
Currently this is what the generated resolvers for model queries look like (a portion of the `req.vtl` file of course):
`#set( $ListRequest = {
  "version": "2017-02-28",
  "limit": $limit,
} )`

There should be away to set the `scanIndexForward` permanently in descending order or ascending at schema creation\modification time. I say permanently because I am assuming there must be some complications and burden for the AppSync team to let clients query DynamoDB table at will in ascending or descending order at application run time. But preferable I would like to see the `sortDirection` parameter become custom just like parameters `nextToken`, `limit` and `filter`. If the `sortDirection` parameter cannot be added, please at least let it be available at schema creation time to set it permanently.

A few months ago the AppSync team created the `@key` directive(The best thing since slide bread), which was wonderful for creating secondary index keys and sort keys.
A solution that I have been thinking about is to include `sortDirection` in the `@key` directive when creating/modifying schema. For Order model, one could define:

`type Order @model @key(fields: ["customerEmail", "createdAt"], sortDirection: "DSC") `

Here the `sortDirection` parameter would be used against the sortKey field: `createdAt`. For people that are not using the `@key` directive, there could be a way `sortDirection` could be targeted at the primary key (Hash key).

**Describe alternatives you've considered**
(1) It was pointed out that I could just log into the aws appsync console and include the "scanIndexForward" to be `false`, as it is `true` by default. However I plan to do that at last resort in case I break something. Evidently It seems that is what I have to do. 

(2) Currently I am doing a reverse after query results returned (very inefficient) luckily I am working with a minimum amount of results.

(3) Spend a couple of weeks(time that I do not have) and learn velocity templating language and write my own resolver.

**Comment by Crisp3333** [comment]
Currently I just log into the aws appsync console choose schema and look for the resolver under query and and just add `"scanIndexForward": false`. Doing this I just have to remember to go back and update it again after each `amplify push`.

**Comment by palpatim** [comment]
@Crisp3333 Thanks for the request and the detailed description of your use case. It seems like this is something we'll need to address either on the CLI side. Since that repo is in a different GitHub org, I've opened issue https://github.com/aws-amplify/amplify-cli/issues/1851 to track this request, and am closing this one.
