### ISSUE TITLE
Uncaught "Call is cancelled" subscription exception

### ISSUE THREAD

**Issue by btilbrook-nextfaze** [awslabs/aws-mobile-appsync-sdk-android#202]
**Describe the bug**
An uncaught exception in the subscription code is crashing Android apps. There is evidently no way to prevent this from occurring.

**To Reproduce**
Not commonly reproducable. Might be a multithreading problem. However, the code in question is obviously a poor way to handle the problem.

**Expected behavior**
The exception is caught and logged or ignored.

**Environment**
 - AppSync SDK Version: `2.10.0`

**Device Information**
 - Device: Pixel 2 API 28 Emulator `29.0.12-5613046`
- Android version: `9.0 (Pie) - API 28`

**Stacktrace**

```
java.lang.RuntimeException: Cancelled
        at com.apollographql.apollo.internal.RealAppSyncSubscriptionCall$1.run(RealAppSyncSubscriptionCall.java:80)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.apollographql.apollo.exception.ApolloCanceledException: Call is cancelled.
        at com.apollographql.apollo.internal.RealAppSyncSubscriptionCall$1.run(RealAppSyncSubscriptionCall.java:80) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by palpatim** [comment]
@btilbrook-nextfaze 

Thanks for the report. If you have any context around cases where you have seen this crash (e.g., what user activity was in process at the time, or led up to the crash), that would be helpful.

**Comment by btilbrook-nextfaze** [comment]
One thing I can say is it seems to be happening when a delta sync subscription is cancelled very shortly after starting.

**Comment by btilbrook-nextfaze** [comment]
The code in question uses a `synchronized (this)` block in attempt to declare a critical section, but appears to be a programming error, because `this` refers to the enclosing anonymous `Thread` instance, which is created anew every time.

**Comment by TrekSoft** [comment]
Sorry for the delay - we'll discuss this on our Friday bug bash

**Comment by TrekSoft** [comment]
Hey, looked into this and you were 100% right about the two issues you raised in that throwing the exception inside the separate thread would always cause the crash and the "this" reference was wrong - I've fixed both of these in the code to rather than throw an exception inside the thread, pass the error back through the callback and we'll now be writing a test to ensure it works before releasing it. Will update this when it's released.

**Comment by btilbrook-nextfaze** [comment]
Great news. Thanks for looking into this - much appreciated!

**Comment by TrekSoft** [comment]
@btilbrook-nextfaze the release that went out last night has the fix - feel free to reopen this issue if you see any more problems with this!
