### ISSUE TITLE
Mixed object in response when using the cache

### ISSUE THREAD

**Issue by Dawen18** [awslabs/aws-mobile-appsync-sdk-android#21]
#### In what version of SDK are you facing the problem? Can you try the latest version?
classpath 'com.amazonaws:aws-android-sdk-appsync-gradle-plugin:2.6.21'
implementation 'com.amazonaws:aws-android-sdk-appsync:2.6.21'

#### Is the issue limited to Simulators or Physical Devices?
Both

#### Is this problem related to a specific API level or Brand?
Tested only on SDK 27

#### Can you give us steps to reproduce with a minimal, complete, and verifiable example?
AppSync client:

```
val appSyncSqlHelper = AppSyncSqlHelper.create(ctx, DB_NAME)
val sqlCacheFactory = SqlNormalizedCacheFactory(appSyncSqlHelper)

// Store Mutations even if application close
val persistentMutationsCallback = object : PersistentMutationsCallback {
    override fun onResponse(response: PersistentMutationsResponse) {
        if (response.mutationClassName == "AddATMMutation") {
            Log.d("SUCCESS PERSISTENT M", response.dataJSONObject.toString())
        }
    }

    override fun onFailure(error: PersistentMutationsError) {
        Log.d("RES_ERROR PERSISTENT", error.mutationClassName)
    }
}

// Set AppSyncSigner
val appSyncSigV4SignerInterceptor = AppSyncSigV4SignerInterceptor(
    BasicAPIKeyAuthProvider(SharedPreferencesProvider.getAppSyncApiKey(ctx)),
    APPSYNC_API_REGION.getName()
)

// Change http client timeouts
val okHttpClient = OkHttpClient.Builder()
    .connectTimeout(HTTP_TIMEOUT, TimeUnit.SECONDS)
    .readTimeout(HTTP_TIMEOUT, TimeUnit.SECONDS)
    .writeTimeout(HTTP_TIMEOUT, TimeUnit.SECONDS)
    .addInterceptor(appSyncSigV4SignerInterceptor)
    .build()

// create appsync appSyncClient
appSyncClient = AWSAppSyncClient.builder()
    .context(ctx)
    .apiKey(BasicAPIKeyAuthProvider(SharedPreferencesProvider.getAppSyncApiKey(ctx)))
    .region(APPSYNC_API_REGION)
    .serverUrl(APPSYNC_API_URL)
    .normalizedCache(sqlCacheFactory)
    .okHttpClient(okHttpClient)
    .defaultResponseFetcher(AppSyncResponseFetchers.NETWORK_FIRST)
    .persistentMutationsCallback(persistentMutationsCallback)
    .build()
```

For exemple with
```
type Country{
    id: ID!
    tag: String!
}

type Color{
    id: ID!
    tag: String!
    hexValue: String!
}
```

1. Load some data on multiple object with network
2. Disable network and access again data. The data are mixed with other objects.

When we query Language, we have some country on the reply

This problem only occurs if we use the cache.

Thanks,
David

**Comment by Dawen18** [comment]
Sorry it was my misunderstanding that led to this error.

I did not understand that the id had to be unique in a global way.

**Comment by AlpacaGoesCrazy** [comment]
Actually id should not be global. Normalized cache should store data with keys which consist of Type name plus id for regular types and Query name with specified parameters for cached query responses.
This is how it works in aws mobile appsync sdk for JS right now. And for android one the cache is simply unusable. 
Just try caching query responses for queries with complex input type parameters (spoiler: it wont find any cached data as android sdk adds some random string for input types in query parameters which makes keys in cache unique for each request even for the same data with same parameters).
This is a very strange behavior for cache.
