### ISSUE TITLE
 W/RetryInterceptor: Encountered IO Exception making HTTP call

### ISSUE THREAD

**Issue by tanujsai** [awslabs/aws-mobile-appsync-sdk-android#213]
**Describe the bug**
In Android 4.x we are observing SSL handshake aborted for subscription initialization. 

 **To Reproduce**
Can be reproduced by using any kitkat (4.4.X) devices 

 **Which AWS service(s) are affected?**
AWS Subscription feature.
  
 **Error Logs**
 ```
09-04 10:05:19.273 2207-2531/com.app W/RetryInterceptor: Encountered IO Exception making HTTP call [javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb9776120: Failure in SSL library, usually a protocol error
    error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x9896d990:0x00000000)]
09-04 10:05:19.273 2207-2531/com.app D/SyncActivity: com.apollographql.apollo.exception.ApolloNetworkException: Failed to execute http call
 ```

**Environment Information**
-- com.amazonaws:aws-android-sdk-appsync:2.10.0
-- com.amazonaws:aws-android-sdk-core:2.13.7
-- org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0
-- org.eclipse.paho:org.eclipse.paho.android.service:1.1.1

 - Device:  Android Studio Emulator
 - Android Version: 4.4.2
 - Specific to simulators: [e.g. Yes/No] Specific to android version 

Can someone please add there input that helps to resolve it.
Thanks in advance

**Comment by desokroshan** [comment]
@tanujsai Thanks for reaching out. We have made changes to the way subscriptions are executed on AppSync as specified in the following Changelog : 
https://github.com/awslabs/aws-mobile-appsync-sdk-android/releases/tag/release_v3.0.0

Can you please update to the latest version of SDK and confirm if the issue persists?

Thanks!
