### ISSUE TITLE
AWS4Signer logs in release variant

### ISSUE THREAD

**Issue by mohamed-khaled-hsn** [awslabs/aws-mobile-appsync-sdk-android#224]
**State your question**
Is there a way to disable AWS4Signer logs?
I'm using Appsync with `"AuthMode": "AWS_IAM"`
and I can see logs even when I'm running release variant containing 
`host;x-amz-date;x-amz-security-token`
why is this intended?

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.8.2

**Device Information (please complete the following information):**
 - Device: Samsung Galaxy S8
 - Android Version: 9

**Comment by kvasukib** [comment]
@mohamed-khaled-hsn Sorry for the inconvenience caused. You can use `LogFactory` to set the log level to a level higher than the level of the signer to avoid getting these logs.

See https://github.com/aws-amplify/aws-sdk-android/issues/1174#issuecomment-548613424 for reference.

**Comment by mohamed-khaled-hsn** [comment]
Resolved by using `LogFactory.setLevel`

**Comment by kvasukib** [comment]
Thank you @mohamed-khaled-hsn for confirming! Closing this issue.
