### ISSUE TITLE
Update to AWS Android SDK v2.16.2 

### ISSUE THREAD

**Issue by jibreel** [awslabs/aws-mobile-appsync-sdk-android#228]
**Is your feature request related to a problem? Please describe.**
The most recent version of the AWS Android SDK fixed an issue causing duplicate users to be created. I opened this issue with support [here](https://us-east-1.signin.aws.amazon.com/oauth?response_type=code&client_id=arn%3Aaws%3Aiam%3A%3A015428540659%3Auser%2Fsupportcenter&redirect_uri=https%3A%2F%2Fconsole.aws.amazon.com%2Fsupport%2Fhome%3Fstate%3DhashArgs%2523%252Fcase%252F%253FcaseId%253D6524961291%2526displayId%253D6524961291%2526language%253Den%26isauthcode%3Dtrue&forceMobileLayout=0&forceMobileApp=0), which was fixed [here](https://github.com/aws-amplify/aws-sdk-android/pull/1284)

**Describe the solution you'd like**
In order to take advantage of the fix, the AppSync SDK needs to update to the most recent version of the AWS Android SDK (v2.16.2). 

**Describe alternatives you've considered**
Because my company's app gets it dependency on the AWS SDK through AppSync, we have no alternatives. 

**Additional context**
Ticket on AWS Android SDK repo [here](https://github.com/aws-amplify/aws-sdk-android/issues/1294)

**Comment by desokroshan** [comment]
@jibreel Thanks for reaching out. The version of the AWS Android SDK in now set to 2.16.3. Please update to the latest version to AppSync SDK to pull in the required changes. Thanks!
