### ISSUE TITLE
Plugin support for Dynamic Feature Module

### ISSUE THREAD

**Issue by sumitzway** [awslabs/aws-mobile-appsync-sdk-android#233]
Hi Team,
I am using AWS appsync in one of my project which required dynamic feature module, but currently `apply plugin: 'com.amazonaws.appsync'` does not applicable due to limitation in **com.apollographql.apollo.gradle.ApolloPlugin.groovy**
however i have download this repo and updated the code as mentioned below
```java
@Override
    void apply(Project project) {
        this.project = project
        if (project.plugins.hasPlugin(AppPlugin) || project.plugins.hasPlugin(LibraryPlugin) || project.plugins.hasPlugin(
                JavaPlugin) || project.plugins.hasPlugin(
                DynamicFeaturePlugin || project.plugins.hasPlugin(
                        InstantAppPlugin))) {
            applyApolloPlugin()
        } else {
            throw new IllegalArgumentException(
                    "Apollo plugin couldn't be applied. The Android or Java plugin must be configured first")
        }
    }
```
now my project is working fine. So its humble request to you please update this code main repo.

**Comment by desokroshan** [comment]
@sumitzway Thanks for reaching out. Would it be possible for you to submit a pull request with the above suggested changes?
