### ISSUE TITLE
AWS App Sync background support

### ISSUE THREAD

**Issue by abhisheksharmacardinal** [awslabs/aws-mobile-appsync-sdk-android#240]
**Does AWS App Sync works in the background and inactive state of application? **

I am planning to get and put data on the server so is it possible to do in the inactive state

**Comment by desokroshan** [comment]
@abhisheksharmacardinal Thanks for reaching out. Can you please clarify what you mean by "inactive" state of the application and what features of AppSync do you want to avail in the inactive state or while the app is in background state?

**Comment by manideepl** [comment]
Hey, I have the same query. Is there something inherently supported in the client that does background work? Meaning, the app is killed, but when the internet is back up, the tasks queued up will still be supported?
