### ISSUE TITLE
Way to add custom HTTP headers

### ISSUE THREAD

**Issue by ekmwilson** [awslabs/aws-mobile-appsync-sdk-android#241]
**Is your feature request related to a problem? Please describe.**
Our team is looking for a way to send application/user specific data in the header of our AppSync queries to be processed by our backend.

**Describe the solution you'd like**
In iOS this is possible using `URLSessionConfiguration` as per the discussion here: https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/161.

Are there any similar known work arounds in Android?

**Comment by murilodag** [comment]
@palpatim You mentioned in the iOS ticket you would reach out to "my colleagues on the Android side". Did you get any response?

**Comment by murilodag** [comment]
Hello @ekmwilson ,

I was able to add the header providing a OkHttpClient.


    val httpClient = OkHttpClient.Builder()
            .addNetworkInterceptor {
                val newRequest = it.request().newBuilder()
                        .addHeader("my-custom-header", "my-custom-value"")
                        .build()
                it.proceed(newRequest)
            }.build()

    appSyncClient = AWSAppSyncClient.builder()
            .context(applicationContext)
            .okHttpClient(httpClient)
            .awsConfiguration(AWSConfiguration(applicationContext))
            .build()

**Comment by ekmwilson** [comment]
Thanks for the suggestion @murilodag ! That works well.
