### ISSUE TITLE
After token expired and sign-in again, new task never be executed

### ISSUE THREAD

**Issue by byteamaze** [awslabs/aws-mobile-appsync-sdk-android#264]
**Describe the bug**
My app use federated sign in and the expired of id-token is 1 hour.
After the id-token expired, we refresh it and re-login, but the future task of AppSync will never execute.
BTW: the aws-mobile-appsync-sdk-ios work fine.

Sign-In code:
```
val providerName = IdentityProvider.DEVELOPER.toString()
AWSMobileClient.getInstance().federatedSignIn(providerName, idToken, options, callback)
```

Init AppSyncClient, singleton instance:
```
this.appSync = AWSAppSyncClient.builder().context(this)
         .credentialsProvider(AWSMobileClient.getInstance())
         .awsConfiguration(awsConfig).build()
```

Fetch user data task:
```
val q = GetUserDataQuery.builder().build()
val call = appSync.query(q).responseFetcher(AppSyncResponseFetchers.NETWORK_ONLY)
         call.enqueue(QLCallbackAdapter { result, error ->
      // If id-token expired and sign-in again, this callback will never call
}
```

**To Reproduce**
1. Federated sign-in use IdentityProvider.DEVELOPER
2. Wait id-token expired
3. Refresh id-token and sign-in again
4. Call fetch user data task or any other task(like mutate), the callback block will never be called.

**Environment(please complete the following information):**
 - AppSync SDK Version: [e.g. 3.0.1]

**Device Information (please complete the following information):**
 - Device: [Any android device]
 - Android Version: [e.g. Nougat 7.1.2, Android 9]

**Comment by byteamaze** [comment]
I've found the solution.
After AWSMobileClient.getInstance().federatedSignIn success, call releaseSignInWait() to release thread lock, or tasks will never be executed.

`AWSMobileClient.getInstance().releaseSignInWait()`

But the sdk should do it automatically.

**Comment by jamesonwilliams** [comment]
@byteamaze Thanks for the feedback, and glad you found a workaround. I agree that the `releaseSignInWait()` is a strange design though... something we will hope to improve in the future.

**Comment by liviu-timar** [comment]
As calling releaseSignInWait() will cancel blocked queries, what is the recommended solution? I have the same problem, queries are never executed after signing-in again.
