### ISSUE TITLE
AppSyncCustomNetworkInvoker JSON parse error when data is null due to mutation validation errors on server

### ISSUE THREAD

**Issue by pthomascelltrak** [awslabs/aws-mobile-appsync-sdk-android#292]
Referenced line assumes that there will always be a data object returned for a mutation. This is not true when validation fails - only the errors field is set. This should probably use optJSONObject.

https://github.com/awslabs/aws-mobile-appsync-sdk-android/blob/8cf6844b16a8f3444d3a9d48b998d2e798445002/aws-android-sdk-appsync/src/main/java/com/amazonaws/mobileconnectors/appsync/AppSyncCustomNetworkInvoker.java#L243

**Comment by doc-rj-celltrak** [comment]
This bug prevents us from learning that an offline mutation eventually fails, unlike iOS. It's only a one-line fix. I hope you can you prioritize it. Thanks!

**Comment by doc-rj-celltrak** [comment]
Hi @jamesonwilliams is there a chance you can address this issue? We believe it's a one-line fix, and it will un-block us. Thanks, we appreciate your help in advance.

**Comment by doc-rj-celltrak** [comment]
@jamesonwilliams ... Just to be clear, the fix is to replace this line:

    persistentMutationsCallback.onResponse(new PersistentMutationsResponse(
        jsonObject.**getJSONObject**("data"), // ...

with this:

    persistentMutationsCallback.onResponse(new PersistentMutationsResponse(
        jsonObject.**optJSONObject**("data"), // ...

**Comment by jamesonwilliams** [comment]
@doc-rj-celltrak thanks, looks reasonable. Our on-call engineer is having a look.

**Comment by changxu0306** [comment]
@doc-rj-celltrak Thanks for your suggestion. We've merged the fixing PR. Will do a release this week.

**Comment by doc-rj-celltrak** [comment]
Great, thanks @changxu0306 and @jamesonwilliams

**Comment by eeatonaws** [comment]
A PR with the fix for this issue was released as part of version 3.1.3.
