### ISSUE TITLE
Completion hander for S3ObjectManager.download()

### ISSUE THREAD

**Issue by michaelschwinges** [awslabs/aws-mobile-appsync-sdk-android#30]
#### In what version of SDK are you facing the problem? Can you try the latest version?

AWS AppSync SDK version 2.6.16

#### Is the issue limited to Simulators or Physical Devices?

Both, I have an API question.

#### Is this problem related to a specific API level or Brand?

No.

#### Can you give us steps to reproduce with a minimal, complete, and verifiable example?
Please include any specific network conditions that might be required to reproduce the problem.

Not applicable.

#### Please include a stacktrace if applicable.

Not applicable.

Hi, I am wondering why in the Android SDK ```S3ObjectManager.download()``` doesn't seem to have a completion handler or callback so one can know when the file has finished downloading?

By way of comparison, in the iOS SDK seems to have a completion handler with success and error. See AWSS3ObjectProtocol.swift. 

Perhaps I am missing something, almost no sample code anywhere that I can find for working with complex objects in an Android app and getting, for example, images into Glide or Picasso to show images.

**Comment by kvasukib** [comment]
@michaelschwinges Thank you for reporting to us. The S3ObjectManager interface exposed provides the contract for upload and download in a synchronous fashion using the PutObject and GetObject methods provided by the AWS Android SDK for S3 low-level interface. 

We will take this as a feature request to the team to support asynchronous interfaces for uploading/downloading files to/from S3.

You can find the documentation for using S3ObjectManager here: https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-android.html#complex-objects Please let us know if this doc provides the code snippet you need.

**Comment by michaelschwinges** [comment]
Thank you for replying so quickly. I'm aware of the link. I hope you don't mind if I give just my own piece of feedback on the documentation in that link and the GitHub example it links to. It's only my experience maybe programmers more experienced than I don't run into these issues, but hopefully it's helpful to the team. 

The document is fairly clear on how to get Complex Objects working, i.e. a bit of fiddling and some setup and it just works (tm) and the object pops right in your S3 bucket linked to the DynamoDB "row" as if by magic. The shortcoming of the documentation and example is that both stop dead in their tracks right there at that point with no guidance or examples on what to do once the file is in S3.

So if one is building an app of any sophistication, e.g. perhaps some personal details in DynamoDB and a profile pic in S3 - or a real estate listing with a pic of the property - then you completely on your own with no guidance from the docs, nothing in the sample project and no examples on the net I can find, either. 

There is a world of difference between being able to upload an image into S3 linked to some fields of data, and having a rich Android or iOS app with database results from DynamoDB mixed with images, presented in a ListView or a RecyclerView with the images being downloaded if needed, cached for a while, and placed into views as needed for you. It's almost as if the API designers designed downloadFile() for apps that placed a PDF file in S3 and perhaps the user taps a button to download it again.

I am trying to use GeneratePresignedUrlRequest to create GET URLs that I can pass to Picasso which will cache and place into views in my ListView, however. I've no idea if this is a right way or a wrong way, I just hope it works when I finish it. No examples anywhere to go on. You can see how a synchronous downloadFile() doesn't help here with a queue of network requests, caching, etc. Over at the competition, Firebase UI 3 supports Glide 4.0 out the box with all the wiring needed for this type of use case, since AppSync is marketed as an App Development solution, it's definitely an important piece of the app development puzzle. Because GeneratePresignedUrlRequest is from s3manager not AppSync, the 1 hour JWT token passed to s3manager has to be constantly refreshed in case the user picks up the app and does something > 1hr after the ListView was generated else one faces authorisation failures. Just feels like should be higher level support in AppSync.

PS I am fairly sure that this grey area around what to do with a complex object once it is in S3 is the very reason that the launch video for AppSync last year used a mapping application: because they could get a visually impressive demo on the stage from two text-only fields latitude and longitude. It's also why the docs stop at the point of file upload to S3 and don't address what next, and it's why the GitHub example project does not use complex objects.

Anyway just my feedback, not to be critical, it comes from a good place and hope it informs further development of AppSync.

**Comment by kvasukib** [comment]
@michaelschwinges Thank you for taking the time to give us detailed feedback. This is valuable to us. I will convey the feedback to the team and we will have a reply to address your concern soon.

**Comment by undefobj** [comment]
@michaelschwinges thanks for your feedback here. I work on both the AppSync and SDK library team and would like to chat with you further if you're open to a phone call. Could you email me richthr_at_amazon.com  (replace the _at_ with @).

**Comment by cbommas** [comment]
@undefobj @michaelschwinges 
I understand that the two of you have synced up offline. I'll go ahead and close out this issue - 
Please feel free to reopen if you believe there are action items that need to be tracked.
