### ISSUE TITLE
How is this different from the Apollo Android client?

### ISSUE THREAD

**Issue by manideepl** [awslabs/aws-mobile-appsync-sdk-android#303]
I know there exists the Apollo client to consume a GraphQL API. But what does this SDK do in addition to the Apollo client? Are there exact features of this SDK listed somewhere?

**Comment by jamesonwilliams** [comment]
Hi manideepl@, the team at AWS created this code base to quickly onboard functionalities that did not exist in the upstream project at that time, in support of AppSync's launch.

The original commits entered this repository as copy-paste of the Apollo codebase, discarding the upstream git history. Based on heuristic info, I believe [the fork occurred](https://github.com/awslabs/aws-mobile-appsync-sdk-android/commit/5ca5670edec8248e048a8fa26e0d7276a79ca5bd) from the `master` branch, somewhere before the [0.5.0 release](https://github.com/apollographql/apollo-android/tree/v0.5.0) of Apollo, which occurred on 17 April, 2018. For reference, [AppSync became generally available](https://aws.amazon.com/about-aws/whats-new/2018/04/aws-appsync-now-ga/) four days before that, on April 13, 2018.

### AppSync Specific Features
This client supports a number of [AppSync-specific features](https://docs.amplify.aws/sdk/api/graphql/q/platform/android) which are not part of the GraphQL specification, and are not included in the Apollo client. (Note: as per the above timeline, AppSync was written against the [2015-2016 specs](https://spec.graphql.org/October2016/), not the later [2018 spec](https://spec.graphql.org/June2018/).) The [SDK documentation](https://docs.amplify.aws/sdk/api/graphql/q/platform/android) mentions these AppSync-specific functionalities, among others:

1. AWS request signing, including [Sig V4](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html), and support for various AWS-specific authentication and authorization strategies ([IAM](https://docs.amplify.aws/sdk/api/graphql/q/platform/android#iam), [Cognito User Pools](https://docs.amplify.aws/sdk/api/graphql/q/platform/android#cognito-user-pools), etc.)

2. [Delta and base sync queries](https://docs.amplify.aws/sdk/api/graphql/q/platform/android#delta-sync), which aim to optimize data consumption from a mobile device.

3. [GraphQL subscriptions via AppSync Realtime](https://docs.aws.amazon.com/appsync/latest/devguide/real-time-data.html)

4. [DynamoDB/S3 hybrid-backed "Complex Objects"](https://docs.amplify.aws/sdk/api/graphql/q/platform/ios#working-with-complex-objects)

5. Code-generation for all of the various [AppSync transforms](https://docs.amplify.aws/cli/graphql-transformer/overview).

### Using Vanilla Apollo

Let's fast-forward to mid-2020. The Apollo open source project is the de-facto standard for transacting with GraphQL endpoints. The [Android client repository](https://github.com/apollographql/apollo-android/commits/master) is a healthy, actively-developed open-source project, seeing a new commit nearly every day. At time of writing, the latest release is [2.2.3](https://github.com/apollographql/apollo-android/releases/tag/v2.2.3), significantly ahead of where the AppSync SDK originated. In some cases ([viz, here](https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/270)), we have needed to back-port important fixes from the upstream codebase.

As an exercise, I recently tried communicating with AppSync using a recent version of Apollo Android, 2.2.0. See [Hitting AWS AppSync from Apollo Android 2.2.0](https://gist.github.com/jamesonwilliams/d3344008eebcb46ee7774ad33ac6ef6c#hitting-aws-appsync-from-apollo-android-220). The most immediately visible gaps are around AWS request signing and authentication, and around support for subscriptions.

### Amplify DataStore

With the exception of a few features, like Complex Objects, the [Amplify DataStore](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/android#datastore-with-amplify) is a newer data management option, which may be a suitable replacement to the AppSync SDK for many customers. Some will find the local data management interface more intuitive to work with, than the AppSync request procedures. The Amplify DataStore handles all of the complexities of speaking GraphQL to AppSync on behalf of the user.

### Current Status (3 Aug 2020)

We are currently supporting the AWS AppSync SDK for Android. Customers are encouraged to evaluate the Amplify DataStore, but may use the AppSync SDK if the DataStore does not meet your project requirements.
