### ISSUE TITLE
Mqtt subscriptions fail when bluetooth printer is connected

### ISSUE THREAD

**Issue by mllrmat** [awslabs/aws-mobile-appsync-sdk-android#31]
I am using appsync subscriptions on a android 5.0.2 device. They work when the device is just connected to the wlan. As soon as I connect a bluetooth printer to the device they fail. Normal queries/mutations work fine, just the subscriptions fail without any message. 
When I restart the app after the printer is connected subscriptions work again. 

I trying this with 'com.amazonaws:aws-android-sdk-appsync:2.6.25'

**Comment by cbommas** [comment]
@mllrmat 

Can you add any logs/stacktraces and a code snippet to help debug this further?

**Comment by cbommas** [comment]
@mllrmat 
I am closing this issue as I haven't heard back from you. Please feel free to reopen if you are still encountering this issue.
