### ISSUE TITLE
Does it work even when the app is killed? If it doesn't how do I make sure it does?

### ISSUE THREAD

**Issue by manideepl** [awslabs/aws-mobile-appsync-sdk-android#310]
For example, the client makes a mutation when offline and the user kills the app later.
How do I get the result of the mutation once the mutation went through? 

There is something like this question already posted:
https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/240

But it doesn't seem to have been addressed.

**Comment by PSIXO** [comment]
Documentation is unclear on this.
There are some work managers being used but it is not explained what happens in these error cases.
Would also like to know the answer to this question?

**Comment by manideepl** [comment]
@PSIXO  Is there any documentation at all related to this? I can't find it.

**Comment by PSIXO** [comment]
Well they just say there is offline support as far as I know:
https://aws.amazon.com/appsync/

**Comment by manideepl** [comment]
But this seems to be related to React Native :(

**Comment by TrekSoft** [comment]
Scroll down a bit to the **Offline Mutations** section of this and see if it addresses your question: https://docs.amplify.aws/sdk/api/graphql/q/platform/android#client-architecture

**Comment by manideepl** [comment]
@TrekSoft Wow, finally! The content there does seem to provide a direction, will try it out and get back. Thank you!

**Comment by SilvestreRamirez** [comment]
find a way to get app sync to work after an app has been killed? I have the same requirement
