### ISSUE TITLE
Subscriptions Not Respecting CognitoUserPoolsAuthProvider Set On Builder

### ISSUE THREAD

**Issue by peter-major-apadmi** [awslabs/aws-mobile-appsync-sdk-android#311]
NOTE: This is similar to issue #257 except it's for a different AuthType 

When creating subscriptions on our AppSync endpoint we get an unauthorized exception. 

On further investigation, we found this is due to the `SubscriptionAuthorizer` class not respecting the `CognitoUserPoolsAuthProvider` set in the `AWSAppSyncClient.Builder`. 

Instead the SubscriptionAuthorizer is hard-coded to use a `BasicCognitoUserPoolsAuthProvider`

This issue affects `com.amazonaws:aws-android-sdk-appsync:3.0.0` and newer

If I rollback to `com.amazonaws:aws-android-sdk-appsync:2.11.0` then the configuration below works as expected.

Here's how we build our AppSyncClient:

```
        val configuration = AWSConfiguration(context)
        val provider: CognitoUserPoolsAuthProvider = MyCognitoUserPoolsAuthProvider()
        AWSAppSyncClient.builder()
            .context(context)
            .cognitoUserPoolsAuthProvider(provider)
            .awsConfiguration(configuration)
            .build();
```

Here's our awsconfiguration.json file:
```
{
  "UserAgent": "aws-amplify-cli/0.1.0",
  "Version": "0.1.0",
  "IdentityManager": {
    "Default": {}
  },
  "CredentialsProvider": {
    "CognitoIdentity": {
      "Default": {
        "PoolId": "...",
        "Region": "eu-west-1"
      }
    }
  },
  "CognitoUserPool": {
    "Default": {
      "PoolId": "...",
      "AppClientId": "...",
      "Region": "eu-west-1"
    }
  },
  "AppSync": {
    "Default": {
      "ApiUrl": "...",
      "Region": "eu-west-1",
      "AuthMode": "AMAZON_COGNITO_USER_POOLS"
    }
  }
}
```

**Comment by peter-major-apadmi** [comment]
Fix provided in this PR:
https://github.com/awslabs/aws-mobile-appsync-sdk-android/pull/312

**Comment by peter-major-apadmi** [comment]
@TrekSoft What's your thoughts on this? 
Do you think the above PR is an appropriate fix for this?
If so, is this something you could action?

We're currently working off a local maven build of the SDK pending this fix, which is fine for development purposes, but not for releasing.

**Comment by TrekSoft** [comment]
Hey, thanks for the PR! I'll ask our on call to take a look at this!

**Comment by richardmcclellan** [comment]
Thanks @peter-major-apadmi!  I've merged the PR, and will plan on doing a release next week.
