### ISSUE TITLE
CACHE_AND_NETWORK Network Failure

### ISSUE THREAD

**Issue by davidhartley** [awslabs/aws-mobile-appsync-sdk-android#314]
In the event of a network failure when using CACHE_AND_NETWORK as the response fetching policy, if a cache is present, no errors are returned in either onFailure or onNetworkError.

Is this expected behavior? Is there a supported way to handle errors during CACHE_AND_NETWORK queries? Or should separate CACHE_ONLY and NETWORK_ONLY fetches be used to be able to handle a case where we want to notify the user of an error while having cache fallback?

**Comment by TrekSoft** [comment]
Hey, AppSync is an older product with none of the original developers still on the team for so can't comment on their original intended behavior with it other than [based on the documentation](https://docs.amplify.aws/sdk/api/graphql/q/platform/android#run-a-query), it seems plausible that's working as expected.

For new development, we recommend evaluating [Amplify DataStore](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/android). We support both products, and you may continue to use the AppSync SDK, if Amplify DataStore doesn’t cover your use case. All the same, we’re working to enumerate any such gaps, and to get them covered in DataStore.
