### ISSUE TITLE
Ability to determine when subscription is connected 

### ISSUE THREAD

**Issue by majsty** [awslabs/aws-mobile-appsync-sdk-android#315]
The iOS SDK provides a `statusChangeHander` which is convenient for determining when the subscription is connected.

As far as I can tell there is no equivalent in the Android SDK. When the websocket connects there is a message in the log like _Subscription created with id = [ID]_ but it would be useful if this also fired something on the `AppSyncSubscriptionCall.Callback`.

**Comment by TrekSoft** [comment]
Hey - it looks like you're right that this does not exist on the Android side. We do provide this functionality in Amplify API which is also now our recommended approach for interacting with AppSync for GraphQL API capabilities: https://docs.amplify.aws/lib/graphqlapi/subscribe-data/q/platform/android

**Comment by majsty** [comment]
> We do provide this functionality in Amplify API which is also now our recommended approach 

This is good to know, but unfortunately it's not feasible for us to migrate to Amplify at this stage of our project. Would you consider including the [Pull Request](https://github.com/awslabs/aws-mobile-appsync-sdk-android/pull/316) for this feature in the next release of the AppSync SDK so those of us that can't migrate to Amplify can still take advantage of this callback?

**Comment by TrekSoft** [comment]
Alright yeah we can take a look at that PR - thanks for submitting it!
