### ISSUE TITLE
App sync subscriptions doesn't return response if something is done when offline.

### ISSUE THREAD

**Issue by SahajRana** [awslabs/aws-mobile-appsync-sdk-android#32]
App sync subscriptions doesn't return response if changes are done in one device, but other device is offline and after sometime turned online.

#### In what version of SDK are you facing the problem? Can you try the latest version?
    implementation 'com.amazonaws:aws-android-sdk-appsync:2.6.20'
    implementation 'com.amazonaws:aws-android-sdk-appsync-compiler:2.6.20'
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
#### Is the issue limited to Simulators or Physical Devices?
Physical device

#### Is this problem related to a specific API level or Brand?
no

```
using simple subscriptions, it works when both device are online, but will not return the previous changes to second device, done by first device when second was offline.
```
It just simply ignores the changes done if the device is offline, and when turned online it receives changes done at that time but not changes done when it was offine.

I think it doesn't queues the changes done but just works on the go.

```
private void subscribe() {
        PutPostSubsSubscription subscription = PutPostSubsSubscription.builder().build();

        subscriptionWatcher = ClientFactory.getInstance(this).subscribe(subscription);
        subscriptionWatcher.execute(subCallback);
    }

    private AppSyncSubscriptionCall.Callback subCallback = new AppSyncSubscriptionCall.Callback<PutPostSubsSubscription.Data>() {
        @Override
        public void onResponse(@Nonnull final Response<PutPostSubsSubscription.Data> response) {
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    Toast.makeText(MainActivity.this, "SubsResponded", Toast.LENGTH_SHORT).show();
                    Log.e("SahajLOG", "ResponseSUBSSSSS**>> " +response.data());
                }
            });

            // Further code can update UI or act upon this new comment
        }

        @Override
        public void onFailure(@Nonnull ApolloException e) {
            Log.e("SahajLOG", "Error::>> " +e);
        }

        @Override
        public void onCompleted() {
            Log.d("Completed", "Completed");
        }
    };

```

**Comment by undefobj** [comment]
In order to get the missed events you will need to re-run a query for the results to populate the cache of a device that was offline. We're working on an enhancement to this functionality in the coming weeks so please stay tuned. However if you'd like to chat offline about this functionality please email me richthr_at_amazon.com (replace the at with @).

**Comment by SahajRana** [comment]
Yaa, after i posted this question, i realized that it might be the reason why it is not there and yaa sure, thanks!

**Comment by cbommas** [comment]
@SahajRana 

The latest version of the SDK 2.7.0 contains support for a sync feature that  will enable you to catch up with changes that your app missed when you were offline. Please see  the Delta Sync section on this page https://aws-amplify.github.io/docs/android/api for more information.

**Comment by SahajRana** [comment]
Thanks, I will look into it!

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue if are still encountering problems.
