### ISSUE TITLE
Requests metadata headers

### ISSUE THREAD

**Issue by myounis97** [awslabs/aws-mobile-appsync-sdk-android#326]
I wondering how could i send request metadata headers like request type **Query/Mutation/Subscription** with every request from Android.

**Comment by richardmcclellan** [comment]
Hi @myounis97,  I don't believe there is a way to set custom HTTP headers on the request.  What use case are you trying to solve with request headers?

**Comment by myounis97** [comment]
We want to create custom WAF filters for certain mutations/queries and we do not want to use regex patterns as they are too costly.
