### ISSUE TITLE
AppSyncOfflineMutationManager seems to block Main Thread on fresh installation of App

### ISSUE THREAD

**Issue by Lavanya2204-developer** [awslabs/aws-mobile-appsync-sdk-android#350]
I tried using the latest SDK to implement App Sync but see below logs repeatedly when I run the application. These logs continuously print when the app is freshly installed and seem to block the UI thread as we see a black screen on the activity on which we are subscribing to events. There is no issue on subsequent launch.

```
V/QueueUpdateHandler: Thread:[13931]: Got message to take action on the mutation queue.
    Thread:[13931]: Got message to process next mutation if one exists.
V/AppSyncOfflineMutationManager: Thread:[13931]:Persistent mutations queue is EMPTY!. Will check inMemory Queue next
    Thread:[13931]: In Memory mutations queue was EMPTY!. Nothing to process, exiting
V/AppSyncOfflineMutationInterceptor: Thread:[13931]: processing Mutations
V/QueueUpdateHandler: Thread:[13931]: Got message to take action on the mutation queue.
    Thread:[13931]: Got message to process next mutation if one exists.
V/AppSyncOfflineMutationManager: Thread:[13931]:Persistent mutations queue is EMPTY!. Will check inMemory Queue next
    Thread:[13931]: In Memory mutations queue was EMPTY!. Nothing to process, exiting
V/AppSyncOfflineMutationInterceptor: Thread:[13931]: processing Mutations
V/QueueUpdateHandler: Thread:[13931]: Got message to take action on the mutation queue.
    Thread:[13931]: Got message to process next mutation if one exists.
```

**Environment:**
 - AppSync SDK Version: 3.1.1

**Device Information:**
 - Device: Samsung S21+
 - Android Version: 11
 - Specific to simulators: No

**Additional context**
FYI, I am trying to subscribe to the App sync client inside `CoroutineScope(Dispatchers.IO)`.
We are using `Amazon Cognito UserPools (AMAZON_COGNITO_USER_POOLS)` as the Authentication mode

**Comment by iamfirdous8** [comment]
Any update on this? I am facing exact same issue.

**Comment by div5yesh** [comment]
Can you please share code snippets and configuration json file with sensitive information removed?

**Comment by iamfirdous8** [comment]
@div5yesh Any update on this issue?

**Comment by poojamat** [comment]
@iamfirdous8 are you initializing appsync sdk in the application class?

**Comment by iamfirdous8** [comment]
Yes @poojamat, It's being initialized in the Application class.

**Comment by poojamat** [comment]
@Lavanya2204-developer the log you have provided suggests that mutation queue is dealt with in a background thread what makes you believe its blocking the main thread?
