### ISSUE TITLE
Execution failed for task ':app:installApolloCodegen'.

### ISSUE THREAD

**Issue by gokulkalagara** [awslabs/aws-mobile-appsync-sdk-android#354]
**Build Failed:**
 Execution failed for task ':app:installApolloCodegen'.

**SDK Version:**
 - AppSync SDK Version:  3.1.0

**Node Install Details : In App Gradle default**
- info using npm@3.10.3
- info using node@v6.7.0
- path node-v6.7.0-win-x64\node.exe

**npm debug files in apollo-codegen**
[npm-debug.log](https://github.com/awslabs/aws-mobile-appsync-sdk-android/files/6766015/npm-debug.log)

**Snapshot Details:**
![Capture](https://user-images.githubusercontent.com/13214923/124511956-e9d8f280-ddf4-11eb-808f-0186a1fcc3b4.PNG)

**Comment by div5yesh** [comment]
Please share your project and app level `build.gradle` file.

**Comment by gokulkalagara** [comment]
For aws-mobile-appsync-sdk-android project also getting same error

**Gradle Details**
[gradle-data.txt](https://github.com/awslabs/aws-mobile-appsync-sdk-android/files/6796439/gradle-data.txt)

**Screenshot Details**
![Capture](https://user-images.githubusercontent.com/13214923/125184716-bacfe000-e23d-11eb-981f-59ace6d6d366.PNG)

**Comment by div5yesh** [comment]
A few questions:
1. Is this on a machine with Apple silicon?
2. Can you share your env. info by running `./gradlew --version` command?

**Comment by gokulkalagara** [comment]
**Machine OS**
Windows 10


**Gradlew Version Details**
Welcome to Gradle 6.7.1!

Here are the highlights of this release:
 - File system watching is ready for production use
 - Declare the version of Java your build requires
 - Java 15 support

For more details see https://docs.gradle.org/6.7.1/release-notes.html


------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_291 (Oracle Corporation 25.291-b10)
OS:           Windows 10 10.0 amd64

**Comment by monochkov** [comment]
I have exactly the same issue on Windows 10 using Gradle 6.7.1. Any updates?

**Comment by gokulkalagara** [comment]
@monochkov 

***You need to change in App Gradle***

node{
download = true
version = "12.18.2"
}

it updates the node inside our project.

**Comment by monochkov** [comment]
@gokulkalagara It's working. Thank you so much!

**Comment by ChulwooJeon** [comment]
@gokulkalagara thank you! I solved my problem this way.

build.gradle (:app) >

android {
     ...
          node { 
               download = true 
               version = "16.13.1" 
          }
}
...

**Comment by eeatonaws** [comment]
Closing this issue since the problem was resolved.
