### ISSUE TITLE
Support Apple Silicon

### ISSUE THREAD

**Issue by timfreiheit** [awslabs/aws-mobile-appsync-sdk-android#355]
Currently it is not supported to use the AppSync gradle plugin on a device running Apple Silicon (M1)

```
Execution failed for task ':data:nodeSetup'.
> Could not resolve all files for configuration ':data:detachedConfiguration9'.
   > Could not find org.nodejs:node:6.7.0.
     Searched in the following locations:
       - https://nodejs.org/dist/v6.7.0/node-v6.7.0-darwin-arm64.tar.gz
     Required by:
         project :data
```

This is due to using node in version `6.7.0` which does not have support for `darwin-arm64`
Node.js does support Apple Silicon since version `16.0.0`

Updating to a newer node version works by using
```
node {
  version = "16.2.0"
}
```

It would be great to have official support for this.

**Comment by div5yesh** [comment]
These changes would be required here: https://github.com/awslabs/aws-mobile-appsync-sdk-android/blob/0435eb2b99d2233e5184d66c588e69596b104360/aws-android-sdk-appsync-gradle-plugin/src/main/groovy/com/apollographql/apollo/gradle/ApolloPlugin.groovy#L33

Currently Node.js v14.17.3 is LTS which does not support Apple Silicon. We should probably wait for v16 LTS release before making this change.

**Comment by msimic-dev** [comment]
According to [this](https://nodejs.org/en/about/releases/) v16 will hit LTS in about 3 weeks. Can we expect any changes this month?

**Comment by damian-lee-km** [comment]
Any plans for a fix for this issue?

**Comment by DanOxlade** [comment]
Really need a fix for this as many more of my colleagues are upgrading to M1 Macs and no longer able to use this plugin.

**Comment by keco1249** [comment]
did this ever get fixed?

**Comment by tylerjroach** [comment]
Thank you for reaching out. Will look to publish the plugin to use a newer version of node compatible with Apple Silicon chips.

**Comment by keco1249** [comment]
awesome, thank you!

**Comment by tylerjroach** [comment]
version 3.4.1 has been released which should allow the gradle plugin to work with Apple Silicon devices!
