### ISSUE TITLE
Android Studio Bumblebee will further break compatibility with Jetpack libraries

### ISSUE THREAD

**Issue by TomBell-Trove** [awslabs/aws-mobile-appsync-sdk-android#381]
Android Studio Bumblebee's 7.1 plugin [will break support for older versions](https://developer.android.com/studio/preview/features#navigation_safe_args_compatibility) of the Navigation Safe Args plugin, requiring that users update to at least Navigation version 2.4.1+.

Currently the latest version of Navigation that works with Appsync is 2.3.0-alpha04... any higher version breaks - see
1. https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/366
2. https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/273

The defect appears to specifically be with Appsync's code generation.

While there are already similar issues open, I feel the need to draw attention to this again.  Bumblebee is currently on RC1 meaning a stable release is imminent.  The state of things is already pretty bad (other jetpack libraries are also incompatible with appsync, such as Jetpack Compose).  The original reported issue is almost 2 years old.

**Comment by constantlyTiTi** [comment]
I am also having the reported issue, and I cannot revert the version back.

**Comment by eeatonaws** [comment]
I apologize for the delay in responding to those issues. We are actively investigating the issue and working on a fix.

**Comment by eeatonaws** [comment]
A fix for the issue has been released in version 3.3.2 of the AWS AppSync SDK for Android.
