### ISSUE TITLE
AppSync codegen models throws @Nullable @Nullable

### ISSUE THREAD

**Issue by sdhuka** [awslabs/aws-mobile-appsync-sdk-android#395]
**Describe the bug**
when I try to build my project I always ran into the following error which does appear for every list item:

error: Nullable is not a repeatable annotation type final @Nullable @Nullable List<Item> items

**To Reproduce**
1) update java poet dependency to 1.13.0.
2) run clean gradle build.
3) Model are generated with duplicate @nullable annotation for list properties.

**Expected behavior**
Only one @nullable annotation should be added.

**Environment(please complete the following information):**
 - AppSync SDK Version: 3.3.1

**Logs**
```
> Task :app:compileDebugJavaWithJavac
/Users/.../app/build/generated/source/appsync/com/amazonaws/amplify/generated/graphql/ListDevicesQuery.java:290: error: Nullable is not a repeatable annotation type
    final @Nullable @Nullable List<Item> items;
                    ^
/Users/.../app/build/generated/source/appsync/com/amazonaws/amplify/generated/graphql/ListDevicesQuery.java:300: error: Nullable is not a repeatable annotation type
    public ListDevices(@Nonnull String __typename, @Nullable @Nullable List<Item> items,
                                                             ^
/Users/.../app/build/generated/source/appsync/com/amazonaws/amplify/generated/graphql/ListDevicesQuery.java:311: error: Nullable is not a repeatable annotation type
    public @Nullable @Nullable List<Item> items() {
                     ^
/Users/.../app/build/generated/source/appsync/com/amazonaws/amplify/generated/graphql/ListProjectItemsQuery.java:301: error: Nullable is not a repeatable annotation type
    final @Nullable @Nullable List<Item> items;
```

**Comment by tjleing** [comment]
We are currently actively working on this issue -- the Javapoet version bump seems to involve a change in the method of storing annotations that causes an unfortunate interaction with our library.

**Comment by tjleing** [comment]
Closed in version 3.3.2.

**Comment by liviu-timar** [comment]
Hi!

I'm using 3.3.2 and I still have the issue. Am I doing something wrong?

implementation 'com.amazonaws:aws-android-sdk-appsync:3.3.2'

Thanks

**Comment by luiss2113-dev** [comment]
I have version 3.2.1, and that version has the same error.
