### ISSUE TITLE
AppSync deletes mutation before calling http that leads to lost of data

### ISSUE THREAD

**Issue by danielvtan** [awslabs/aws-mobile-appsync-sdk-android#40]
**Describe the bug**
PersistentOfflineMutationManager.java deletes mutation even before successful http call leads to data loss

**Expected behavior**
mutation should only be deleted after a successful http call
deletion of mutation should be call after httpCall.enqueue on success response
should be retried on fail
.

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.6.25+

**Additional context**
`
// PersistentOfflineMutationManager.java

public PersistentOfflineMutationObject removeAndGetLastInQueue() {
        if (persistentOfflineMutationObjects.size() >= 1) {
            PersistentOfflineMutationObject mutationObject = persistentOfflineMutationObjects.remove(0);
            mutationSqlCacheOperations.deleteRecord(mutationObject.recordIdentifier); // <- deletes before http success
            return mutationObject;
        }
        throw new IllegalStateException("Persistent Mutation Queue is empty. Cannot remove object.");
    }`

**Comment by cbommas** [comment]
@danielvtan 

Wanted to let you know that I am looking into this as part of my investigation into #33

**Comment by cbommas** [comment]
@danielvtan 

Version 2.7.1 of the SDK contains queuing logic to address the issue that you reported. Please upgrade to this version and let us know how you fare. 

I will close this thread and lets use #33 for tracking purposes.
