### ISSUE TITLE
AWS appsync doesn't build with agp version 8.0

### ISSUE THREAD

**Issue by sharadsmhaske** [awslabs/aws-mobile-appsync-sdk-android#410]
**Describe the bug**
We are not able to upgrade the agp version in our app as app sync doesn't build with agp 8.0

**To Reproduce**
Update the version of app with agp 8.0.
Try building the app with app sync latest version.
We are getting below error :
A problem occurred configuring project ':app'.
> Could not create task ':app:generateProdDebugApolloClasses'.
   > Cannot use @TaskAction annotation on method ApolloClassGenTask.generateClasses() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.

**Expected behavior**
It should build the code. Please let us know workaround if available to support agp 8.0

**Comment by mattcreaser** [comment]
Thanks for the report @sharadsmhaske, we will take a look.

**Comment by lolucosmin** [comment]
+1 Also receiving this error if attempting to use Android Gradle Plugin 8.0

**Comment by mattcreaser** [comment]
A fix has been released in Appsync SDK [3.4.0](https://github.com/awslabs/aws-mobile-appsync-sdk-android/releases/tag/release_v3.4.0). Please let us know if you have any additional questions.

**Comment by fcoconstante** [comment]
It worked, in agp version 8.1.0 and appsync-gradle-plugin:3.4.0, the docs, here  says: 

classpath 'com.amazonaws:aws-android-sdk-appsync-gradle-plugin:3.2.1'

implementation 'com.amazonaws:aws-android-sdk-appsync:3.3.1'

I guess that they need to be updated. Thanks!
