### ISSUE TITLE
Subscriptions are closed when wifi is disabled even if there is a cellular connection.

### ISSUE THREAD

**Issue by timowilson-fluke** [awslabs/aws-mobile-appsync-sdk-android#45]
**Describe the bug**
Mutation subscriptions are closed when wifi is disabled even if there is a cellular connection available. The "onCompleted" method of the subscription callback is called when wifi is disabled. And "re-subscribing" during the "onCompleted" method will result in a exception being thrown.

**To Reproduce**
1. Start a subscription for a mutation.
2. Turn WIFI off on the Android device.
3. Note that the subscription callback "onCompleted" method is triggered. Indicating that the subscription has been canceled.

**Expected behavior**
Since there is still a connection available (cellular) I would expect that the subscription would stay active and continue. In general, I'm not sure why the subscription is canceled even if all connectivity is lost. Couldn't it hang around and wait till a connection is reestablished?

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.6.26

**Device Information (please complete the following information):**
 - Device: Samsung S9
 - Android Version: Oreo 8.0

**Comment by cbommas** [comment]
@timowilson-fluke 

We are working on including reconnect capability in the SDK for subscriptions to handle unexpected disconnects. I  am hoping to get this included in the next rev of the SDK. I will post back on this thread once I have confirmation.

**Comment by Rissmon** [comment]
@cbommas 
Hi,
We are facing the same issue with AWS AppSync SDK. Any update regarding the planned date for the next release version of SDK.

**Comment by cbommas** [comment]
@Rissmon 

I don't have a final date yet. I will let you know once I have more information - unfortunately, this fix did not make it into v2.6.27

**Comment by cbommas** [comment]
@Rissmon 
The latest version of the SDK 2.7.0 has the reconnect capability built into it. With this functionality, the subscription will be automatically retried and setup if it were to go down due to temporary network outages or transitioned from one network to the other.

**Comment by timowilson-fluke** [comment]
Thanks, I'll try it out.

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue if are still encountering problems.
