### ISSUE TITLE
Does the cached credentials renew automatically when creating mutation offline?

### ISSUE THREAD

**Issue by danielvtan** [awslabs/aws-mobile-appsync-sdk-android#46]
**State your question**
Login online
Add cached credentials provider for access to s3
Go offline
Create mutation with s3 upload
Wait until expiration
Go online
Does the cached credentials renew automatically and complete the mutation? 
Or will the mutation fail?

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.6.+

**Comment by cbommas** [comment]
@danielvtan 

The cached credentials will be renewed if required ( they will only be fetched if the SDK detects that the credentials have expired ) and the mutation will be completed.

I am curious about the question - are you running into issues and suspecting credentials failures?
If so, can you please provide stacktraces/code snippets to help debug.

**Comment by danielvtan** [comment]
@cbommas 

I asked here before i tested yesterday because it takes at least an hour to test this. 
I already tested it and i was having issues. I cannot post the stacktrace because i already made a solution and can't wait for an hour to test it again.
The issue happens when i make a mutation offline then go online after an hour.
Error is something like  "token is already expired with timestamp < timestamp".

i would like to know where can i find the renewing of cached credentials.

Thank you

**Comment by cbommas** [comment]
@danielvtan 
I have verified that with the fixes in 2.7+, the credentials will be refreshed and the mutation successfully executed. The renewal of credentials happens automatically within the SDK. See the following links

https://github.com/awslabs/aws-mobile-appsync-sdk-android/blob/1f3cbfb27b6ec2370d5befbb4559641d47b8c0ff/aws-android-sdk-appsync/src/main/java/com/amazonaws/mobileconnectors/appsync/sigv4/AppSyncSigV4SignerInterceptor.java#L139

https://github.com/awslabs/aws-mobile-appsync-sdk-android/blob/1f3cbfb27b6ec2370d5befbb4559641d47b8c0ff/aws-android-sdk-appsync/src/main/java/com/amazonaws/mobileconnectors/appsync/sigv4/AppSyncSigV4SignerInterceptor.java#L154

https://github.com/awslabs/aws-mobile-appsync-sdk-android/blob/1f3cbfb27b6ec2370d5befbb4559641d47b8c0ff/aws-android-sdk-appsync/src/main/java/com/amazonaws/mobileconnectors/appsync/sigv4/AppSyncSigV4SignerInterceptor.java#L161

I will go ahead and close this issue - please feel free to reach back if you are still running into issue.

**Comment by danielvtan** [comment]
@cbommas thanks for the fixes. Currently i can not test this as we are using a modified version of the sdk. We will test this for our next project.
