### ISSUE TITLE
Subscriptions with IAM does not work propely

### ISSUE THREAD

**Issue by sargentin** [awslabs/aws-mobile-appsync-sdk-android#5]
I'm using IAM authentication (access key and secret key), so that users can share their locations in real-time. For that, I created a subscription that works fine in queries console of AppSync. But when I implemented it in my app, it does not work properly.

Here is a use case :

1. user A access to the map, see his location, and a subscription is opened to locations
2. user B does the same thing
3. user A send his last location
4. user B receive it, and user A appear on the user B map
5. user B send his last location, but user A never receive it

Sometimes if user A leave the map and come back to it, with a subscription newly opened, he receive the last user B location sent after that subscription, and after that no location is received even if user B continue to send his locations.

**Comment by minbi** [comment]
Hi @sargentin ,

Do you see any errors being reported in the `onFailure` callbacks when user B sends his location?
Are you trying this on two devices or are you using one device for both user A and B?
Would you be able to share any code?

Standard info questions:
Which SDK version are you using? latest is 2.6.17
Is this device or emulator?

**Comment by sargentin** [comment]
Hi @minbi,

I use two real devices, and sometime add an emulator.
The SDK version is the latest 2.6.17.
I read your answer about WeakReference class, I'll take a look at this.
Finally, because of the short time remaining to complete my app, I choose to replace the subscription by calling my location graphql query every X seconds.

Best regards,

Steeve
