### ISSUE TITLE
Subscriptions Not Triggering Sometimes Even Though There Is Stable Internet

### ISSUE THREAD

**Issue by manum176** [awslabs/aws-mobile-appsync-sdk-android#54]
We are using the SDK for an android project. When the mutations are triggered from backend (Lambdas, APIs, etc.) the subscriptions are not getting invoked sometimes even though the internet connection is stable. After 3-4 retries, it will get invoked

**Expected behaviour**
The subscriptions should trigger in any case if there is a stable internet connection

**Environment:**
 - AppSync SDK Version: 2.6.26

**Device Information:**
 - Device: Samsung J8, Redmi Note 5 Pro
 - Android Version: Marshmallow 6.0, Oreo 8.1

Thanks in advance

**Comment by cbommas** [comment]
@manum176 

Sorry to hear that you are running into issues. One of the areas to look into is to check if your subscriptions are active and not disconnected.  Can you post logs from your logcat ( at the verbose setting) and I can look through to see if there are any connection drops. Also, can you share a code snippet from your app - specifically the subscription and the callback logic?

**Comment by cbommas** [comment]
@manum176 

The latest version of the SDK 2.6.27 contains a fix to set to the QoS to 1, which will give you at least once message delivery.  Please try this out and let us know how you fare.

**Comment by manum176** [comment]
@cbommas 
Thanks

Since the realtime updates were much critical for our project, we could not continue on with AppSync. So we moved to some alternate solutions and hold AppSync for the time being.

However, we will check this and let you know.

**Comment by cbommas** [comment]
@manum176 
sorry to hear that. Please let me know if you'd be willing to jump on a call with us to discuss your usecases/scenarios and the issue that you faced.

**Comment by manum176** [comment]
@cbommas 
Yes, we are ready for a call to discuss the issues. Please let me know how I can contact you

Thanks

**Comment by cbommas** [comment]
@manum176 

Excellent. Please email ( chabom at amazon.com ) and I can get a bridge setup and invite folks from my side.

**Comment by cbommas** [comment]
@manum176 

Just checking back as I haven't heard from you via email.

**Comment by cbommas** [comment]
@manum176 
Apologies - i see that you sent me an email earlier today. Lets continue the conversation there.
