### ISSUE TITLE
How to receive pending subscription on Android app, when it restarts after a force close?

### ISSUE THREAD

**Issue by intellignt-idiot** [awslabs/aws-mobile-appsync-sdk-android#58]
I am using AppSync version 2.6.+ . I checked , when I force close the app and a subscription is triggered, it is not received by the app. This is because my app was force closed or was completely closed.

Now when I restart my app, I still do not get that pending subscription. Does it mean, if I miss a subscription, I will never receive it ? The only way is to manually query for that particular table and update my data.

Thanks in Advance.

**Comment by cbommas** [comment]
@intellignt-idiot 

Unfortunately, what you have observed is how the system currently works.  If your app is closed when a mutation triggers your subscription, that message will not be received by the app. 

When you restart the app and re-subscribe, the system will treat is as a new subscription and will not send the pending/missing messages from the previous subscription to it. So the only way to get those updates is to manually query the particular table/entity.

That said, we have some features in the works that will help with this situation. I will let you know on this thread or through a forum announcement when I have more information.

**Comment by intellignt-idiot** [comment]
@cbommas 

Alright. Thanks for the clarification. Waiting for a solution in the upcoming versions.

**Comment by cbommas** [comment]
@intellignt-idiot 

Sounds good. I will close out this issue.
