### ISSUE TITLE
How to handle multiple subscriptions in Android?

### ISSUE THREAD

**Issue by richienko** [awslabs/aws-mobile-appsync-sdk-android#59]
**State your question**
How to handle multiple subscriptions in Android? Can someone post working snippet? I get working only first initialized subscription in application. 
I'm not using API key authorization.

**Provide code snippets (if applicable)**
```Subscription1 sub1 = Subscription1.builder().build();
Subscription2 sub2 = Subscription2.builder().build();

sub1Watcher = appSyncClient.subscribe(sub1);
sub2Watcher = appSyncClient.subscribe(sub2);

sub1Watcher.execute(sub1Callback);
sub2Watcher.execute(sub2Callback);
```
Everytime only sub1 is executed.

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.6.25

**Device Information (please complete the following information):**
 - Device: Simulator

Thanks.

**Comment by cbommas** [comment]
@richienko 

Release 2.6.26 had a bunch of fixes around the subscription logic. Can you upgrade to the latest version and try again?

Also, here is an example of how multiple subscriptions work.
https://github.com/awslabs/aws-mobile-appsync-sdk-android/blob/03d8d3b5995eff87073bdb4b0cd142c2942c1ef1/aws-android-sdk-appsync-tests/src/androidTest/java/com/amazonaws/mobileconnectors/appsync/AWSAppSyncQueryInstrumentationTest.java#L231

**Comment by richienko** [comment]
Yep, it helped a lot.
Thank you very much @cbommas !
