### ISSUE TITLE
App crashes when app is running

### ISSUE THREAD

**Issue by huforrest** [awslabs/aws-mobile-appsync-sdk-android#60]
App crashes when app is running especially when app come into foreground from background. I guess that the problem lies in the cached database. The cursor is not closed when executing the database operation. And here is the snapshot of the crash log.
![488499a5-d644-4b8c-81fb-8a63693831fd](https://user-images.githubusercontent.com/23306480/48527878-8d350c00-e8c7-11e8-9c89-bb5e04d578d2.png)

**Comment by muellerfr** [comment]
Hello @huforrest,

Do you have a call stack or repo steps you can share with us?

**Comment by huforrest** [comment]
We are developing a chat app. Sorry to tell you that it is difficult to provide you sample code, call stacks or repo steps. For now we can only provide you the appsync SDK. Appsync SDK: v2.6.27. The bug occurs sometimes. Yesterday we installed the bug collecting tools. And when the bug occurs again, I will tell you the detail information.

**Comment by cbommas** [comment]
@huforrest 

It is not possible to make progress on the issue without the sample code/stacktraces and repo steps. I will go ahead and close this issue - please reopen this issue ( or open a new one) when you have more data.
