### ISSUE TITLE
RealSubscriptionManager: No listeners for message

### ISSUE THREAD

**Issue by 472574155** [awslabs/aws-mobile-appsync-sdk-android#71]
**Describe the bug**
W/RealSubscriptionManager: No listeners for message: {"data":{"onUpda......
Callback does not work properly.

Code:
OnCreateMessageSubscription onCreateMessageSubscription = OnCreateMessageSubscription
                .builder()
                .build();
onCreateMessageWatcher = appSyncClient.subscribe(onCreateMessageSubscription);        onCreateMessageWatcher.execute(new AppSyncSubscriptionCall.Callback.....);

When my app turn to background, I shutdown the subscription.
`onCreateMessageWatcher.cancel();`
`onCreateMessageWatcher = null;`

And when I resumed app, I regisitered the watcher again.

Do it like this as soon as possiable several times.
This subscription can't bring the messages to my callback any more.

**Environment(please complete the following information):**
 - AppSync SDK Version: [2.6.28]

**Comment by palpatim** [comment]
Hi @472574155, the 2.7.0 release of the AppSync SDK includes support for "catch up" queries when reconnecting, and included some bug fixes around reconnection logic. Does this issue persist using the latest SDK version?

Also, for clarification, when you say "Do it like this as soon as possiable several times", do you mean, you background and foreground the app rapidly several times in succession to trigger this issue?

**Comment by 472574155** [comment]
@palpatim 
"background and foreground the app rapidly several times in succession to trigger this issue"   YES

**Question when updated AppSync SDK Version to 2.7.0**
When I updated AppSync SDK Version to 2.7.0 , my application can no longer working as well.
When applicaition started, UI action can not be triggered. Application jammed.

**Comment by cbommas** [comment]
@472574155 
sorry to hear that you are running into issues. I will look into this further. It would be great if you can post the contents of your logcat.

One thing I'd like you to try - can you remove the code to cancel and null out the subscription when the app goes to the background? 

The latest version of the SDK has automatic reconnection logic built into it and you don't need to do special handling for background and foreground.

**Comment by 472574155** [comment]
@cbommas 
I removed the code to cancel and null out the subscription when the app goes to the background.
But there has another question happened.
When I close a chat room as soon as the room just opened, app's UI actions have no response.
It may be a question that subscription had been cancled before it had been init completed.

**Comment by cbommas** [comment]
@472574155 
Did the change I suggested fix the issue that you were having regarding messages making it to the callback? If so, lets close this issue and open a new one for the other question that you had.

I am just trying to keep one problem in one thread - will be helpful to others that facing similar issues.

**Comment by 472574155** [comment]
@cbommas 
Although new happened question is the same to the issue, I will close this issue and continue to focus on #75 .
