### ISSUE TITLE
If subscriptionWatcher cancel too early. App is not opened

### ISSUE THREAD

**Issue by yhkwon44** [awslabs/aws-mobile-appsync-sdk-android#75]
My Code like this
onCreate
```
subscriptionWatcher = ClientFactory.getInstance(mAuthProvider, mContext.getApplicationContext()).subscribe(subscription);
        subscriptionWatcher.execute(subscriptionCallback);
```

onDestroy
`subscriptionWatcher.cancel();`

When I reopen the APP after APP closed as soon as APP is opend
My App is no response. 

simply 
1. open the App
2. close the App Immediately.
3. reopen the App
4. No response.. just white. 

* I'm in Seoul And my Appsync Server is in Ireland.. So All query is slow

**Comment by cbommas** [comment]
@yhkwon44 

Can you post your logs? Is this the onCreate of your main activity. Also, you mentioned a white screen - how are you loading the main screen? Are you using an AppSync query?

**Comment by cbommas** [comment]
Closing as I haven't heard back. Please feel free to reopen if you are still running into issues.
