### ISSUE TITLE
One object for Query and Subscription?

### ISSUE THREAD

**Issue by richienko** [awslabs/aws-mobile-appsync-sdk-android#76]
**State your question**
I have query which returns `PersonConnection` type, subscription which is returning `Person` and mutation for update values. Below is the scheme.

Right now I have to use:
1. OnUpdatePersonSubscription.Data.OnUpdatePerson
2. UpdatePersonMutation.Data.UpdatePerson
3. ListPersonsQuery.Data.listPersons.items

So right now when all fields for person are updated and subscription is fired. And I don't want to fetch data again, I just want to update current Person data in UI, I have to manually update every field.
As the mutation, query and subscription returns same **return** values (id, name, address), is it possible to generate android classes which are using same objects?

**Code snippets:**

**AWS Appsync Console**
```
type PersonConnection {
	items: [Person]
	nextToken: String
}

type Person {
	id: ID!
	name: String!
	address: String
}

listPersons(limit: Int, nextToken: String): PersonConnection

onUpdatePerson(id: String): Person
		@aws_subscribe(mutations: ["updatePerson"])

updatePerson(input: UpdatePersonInput!): Person
```

**Android graphql file**
```
query ListPersons($limit: Int, $nextToken: String) {
  listPersons(limit: $limit, nextToken: $nextToken) {
    items {
        id
        name
        address
    }
    nextToken
  }
}

mutation UpdatePerson($input: UpdatePersonInput!) {
    updatePerson(input:$input) {
        id
        name
        address
    }
}

subscription OnUpdatePerson($id: String!) {
  onUpdatePerson(id: $id) {
    id
    name
    address
  }
}
```

**Environment:**
 - AppSync SDK Version: 2.6.26

**Comment by cbommas** [comment]
@richienko 

You should be able to accomplish this using fragments - See https://github.com/aws-samples/aws-mobile-appsync-events-starter-android/blob/43c60142e5a6cd5dbf1575c96dbdf93110f964a2/app/src/main/graphql/com/amazonaws/demo/appsync/events.graphql#L48 for an example of how it is used.

**Comment by richienko** [comment]
That's it!
Thanks a lot.
