### ISSUE TITLE
Subscription Gotchas 

### ISSUE THREAD

**Issue by leijdekkers** [awslabs/aws-mobile-appsync-sdk-android#78]
For those trying to get Subscriptions to work in their Android app and follow the sample app. The documentation leaves out some details (but are in the code which you can easily overlook!) that are essential to get Subscriptions to work in your app. 

Note to AWS: Please update your description of the demo app and include a section on what to do to get subscriptions to work. 

**1. Manifest File**
Check that you have the following permissions specified:
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
```

Check that you have added the following service
`<service android:name="org.eclipse.paho.android.service.MqttService" />`

**2. app.gradle**
Add these libraries
```
 implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
 implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
```

**Comment by cbommas** [comment]
@leijdekkers 

Thank for reporting this. I will get the README and documentation updated.

**Comment by cbommas** [comment]
@leijdekkers 

The sample app README and the documentation are updated ( documentation is at https://aws-amplify.github.io/docs/android/api#import-sdk-and-config).

I will go ahead and close this issue. Please feel free to reopen if you have further items that need addressing.
