### ISSUE TITLE
How to add logging interceptor?

### ISSUE THREAD

**Issue by kpjofficial** [awslabs/aws-mobile-appsync-sdk-android#92]
I am new to GraphQL and AWS. I am using `AWSAppSyncClient` to make the API calls. I need to see the response like `HttpLoggingInterceptor` in `Retrofit`. I have tried looking, but no luck.

TIA

**Comment by kpjofficial** [comment]
Ok. It turns out probably there are no solution to achieve Monitoring and Logging in Android, but [Amazon Cloudwatch](https://aws.amazon.com/cloudwatch/) can be useful from [here](https://docs.aws.amazon.com/appsync/latest/devguide/monitoring.html).

I have started using Cloudwatch and although it is not exactly as I needed, it gets the work done but, that solution in the Android can be really useful and convenient.

**Comment by cbommas** [comment]
@kpjofficial 
You can implement your own LoggingInterceptor,  attach it to a OkHTTP client and pass that client into `AWSAppSyncClient`.

You would do that as follows

      AWSAppSyncClient.builder()
                    .context(context)
                    .okHttpClient(null)
                    .credentialsProvider(getCredentialsProvider(context)) 
                    .region(Constants.APPSYNC_REGION)
                    .serverUrl(Constants.APPSYNC_API_URL)
                    .okHttpClient(new OkHttpClient.Builder()
                            .addInterceptor(yourCustomLoggingInterceptor)
                            .build())
                    .build();

Let me know if you run into any issues doing this.

**Comment by kpjofficial** [comment]
I do not know how to create LoggingInterceptor, I added `OkHttpLoggingInterceptor` using 

```
implementation 'com.squareup.okhttp3:logging-interceptor:3.12.0'
implementation 'com.squareup.okhttp3:okhttp:3.12.0'
```

and followed as you've shown. It works but is this way acceptable? or could have that done better?

Thank you @cbommas

**Comment by cbommas** [comment]
@kpjofficial 
That way is fine as well. Glad that it worked out for you. 
I will close this thread. Please feel free to reach back if you run into issues.
