### ISSUE TITLE
Conflict resolution does not work after relaunch app

### ISSUE THREAD

**Issue by santosdaniel** [awslabs/aws-mobile-appsync-sdk-android#95]
**For ignoring a conflict in the client side we need to call more that handler.fail(recordIdentifier) ?**
I am trying to implement a conflict revolver in my android client, in my case there is the possibility the of two messages have the same identifier since there are periods which my users are going to be offline.
If my conflict resolver is called without restarting the application the conflict resolver works just fine.
If there is a restart of the application the mutation queue gets stuck.

**To Reproduce**
1. Using two devices disable the network of one them 
2. In the device online send create one entity with id = '1'
3. With device offline try to send an entity with id='1' (Putting the mutation in the queue)
4. In the device offline force the application that uses the sdk to stop.
5. In the device offline relaunch the application using the sdk.
6. In the device offline put it online again.
7. The conflict revolver is going to be called if configured 'AWSAppSyncClient.builder().conflictResolver(myConflictResolver)'

In this conflict revolver should have something like ' handler.fail(recordIdentifier)' or I need to 
call anyother method to not get my queue stuck ?

**Environment:**
 - AppSync SDK Version: 2.7.3

**Device Information:**
 - Samsung gallaxy tab

**Comment by cbommas** [comment]
@santosdaniel 

Sorry to hear that you are running into issues. I will look into this and get back to you.

**Comment by santosdaniel** [comment]
Additional info: As far as I could see in my case the method getFirstInQueue() of the class PersistentOfflineMutationManager is returning always the same element to be sent to the network.

This method getFirstInQueue() uses the list persistentOfflineMutationObjectList which does not get clean by the call to handler.fail(recordIdentifier),
This is why I first thought that was a bad use of the Api of my part or if I need it to call another method to remove the element from this list persistentOfflineMutationObjectList.

**Comment by cbommas** [comment]
@santosdaniel 

Version 2.7.5 of the SDK contains fixes for this issue. Please try it out and let me know how it goes.

**Comment by ukevgen** [comment]
@cbommas seems in 2.7.5 doesn't work properlyy https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/102

**Comment by cbommas** [comment]
@ukevgen 
Lets follow that issue on #102. I will go ahead and close out this issue with the conflict management as I got confirmation on #98 that the issue was resolved.
