### ISSUE TITLE
Check if mutationQueue empty?

### ISSUE THREAD

**Issue by gitnarqt** [awslabs/aws-mobile-appsync-sdk-android#96]
Is there a way to know if the mutationQueue is empty? We want to make sure that all mutations were carried out before logging out a user.

**Comment by cbommas** [comment]
@gitnarqt 

At this time, there isn't an API/method that you can invoke in the AppSync SDK to know if the mutationQueue is empty.  

One idea that you can explore - since mutations will receive an `onResponse` and `onFailure` callback, may be you can use that to keep track of Mutations?

**Comment by gitnarqt** [comment]
thank you for your response! Are there plans to implement this feature in the near future?

**Comment by cbommas** [comment]
@gitnarqt 

We will take this as a feature request and provide an update here once this is prioritized and we have a timeline established.

**Comment by gitnarqt** [comment]
Awesome, thank you so much!

**Comment by cbommas** [comment]
@gitnarqt 

v2.7.6 contains the mechanism to check if the mutation queue is empty. See the link below for an example of how to use it.

https://github.com/awslabs/aws-mobile-appsync-sdk-android/blob/1dd1fd9959837438896bd4aa39f8de5c426a23b7/aws-android-sdk-appsync-tests/src/androidTest/java/com/amazonaws/mobileconnectors/appsync/AWSAppSyncQueryInstrumentationTest.java#L1197

**Comment by gitnarqt** [comment]
@cbommas awesome! Worked like a charm, thank you for the prompt update.

**Comment by cbommas** [comment]
@gitnarqt 
Thank you for confirming! I will go ahead and close out this issue.
