### ISSUE TITLE
selectedAuthMode is null in AWSAppSyncClient.java - causes Exception on AWSAppSyncClient.Builder.build() - Android Client

### ISSUE THREAD

**Issue by imhashir** [awslabs/aws-mobile-appsync-sdk-android#97]
Hi!
I have just started using AWS Amplify and came across some issues. My app logs in perfectly and on restarting the app, the UserState is **SIGNED_IN**
But when I try to build an appsync client it gives the following exception:

> RuntimeException: Please check the AppSync configuration in awsconfiguration.json.

I am just testing AppSync and Amplify so the code is pretty basic. Here is the code:

```
AWSMobileClient.getInstance().initialize(applicationContext, object : Callback<UserStateDetails> {
            override fun onResult(result: UserStateDetails?) {
                when(result!!.userState) {
                    UserState.SIGNED_IN -> {
                        Log.i("TEST", "Signed In")
                        awsAppSyncClient = AWSAppSyncClient.builder()
                                .context(applicationContext)
                                .awsConfiguration(AWSMobileClient.getInstance().configuration)
                                .build()
                    }
                    else -> {
                        AWSMobileClient.getInstance().signOut()
                        Log.i("TEST", "Signed Out")
                    }
                }
            }

            override fun onError(e: Exception?) {
                e!!.printStackTrace()
            }

        })
```

I debugged a bit deeper and found that in the **AWSAppSyncClient.java** file, the **selectedAuthMode** stays null. I wasn't able to find out where is it being assigned but the **authMode** that takes auth mode value from json file is picking correct value from json. i.e. **AMAZON_COGNITO_USER_POOLS**
It fails at **line no 487** of **AWSAppSyncClient.java** where it tries to show exception of:

```
throw new RuntimeException("Found conflicting AuthMode. Should be " +
                                authMode.toString() + " but you selected " + selectedAuthMode.toString());
```

but since the selectedAuthMode is null, it gives NullPointerException instead of showing the actual exception. I am not sure why its null. Because on Amplify console, correct auth mode is selected. Have a look at screenshot below:

![issue_aws_console](https://user-images.githubusercontent.com/10235172/51072333-b9c79300-1680-11e9-95ca-326f428c2580.PNG)

Is there something wrong with my approach or configurations or is it a bug in amplify? 
Any kind of help would be highly appreciated.
Thanks.

**Comment by imhashir** [comment]
So looks like I could solve it. It wasn't an issue in sdk. It was just not clear enough in documentation. Here is the code that worked:
```

awsAppSyncClient = AWSAppSyncClient.builder()
                                .context(applicationContext)
                                .region(Regions.US_EAST_2)
                                .cognitoUserPoolsAuthProvider(BasicCognitoUserPoolsAuthProvider(cognitoUserPool))
                                .awsConfiguration(AWSMobileClient.getInstance().configuration)
                                .build()
```

I was not specifying cognitoUserPoolAuthProvider. I did and it worked. Thanks to the sample code. That helped.

**Comment by muellerfr** [comment]
Hi @imhashir, the user pools configuration is documented here: https://aws-amplify.github.io/docs/android/api#cognito-user-pools Can you please review and let us know if this would have answered your question? If so, what could we have done to make the documentation easier to find?

**Comment by devxpy** [comment]
@muellerfr Maybe tell us how to get the `AWSAppSyncClient` object properly setup _before_ telling how to run a query? 
Like the "Authentication Modes" section should have been a part of "Client Initialization", really.

**Comment by muellerfr** [comment]
@devxpy thank you for your suggestion - I've created a new issue in our docs repo to track this suggestions. https://github.com/aws-amplify/docs/issues/427 Please follow the issue for updates. Also, since the documentation is Open Source feel free to submit a PR!

**Comment by jonneymendoza** [comment]
> So looks like I could solve it. It wasn't an issue in sdk. It was just not clear enough in documentation. Here is the code that worked:
> 
> ```
> 
> awsAppSyncClient = AWSAppSyncClient.builder()
>                                 .context(applicationContext)
>                                 .region(Regions.US_EAST_2)
>                                 .cognitoUserPoolsAuthProvider(BasicCognitoUserPoolsAuthProvider(cognitoUserPool))
>                                 .awsConfiguration(AWSMobileClient.getInstance().configuration)
>                                 .build()
> ```
> 
> I was not specifying cognitoUserPoolAuthProvider. I did and it worked. Thanks to the sample code. That helped.

How did you create the "cognitoUserPool" object?

**Comment by connorblairmn** [comment]
@jonneymendoza this is how I created the cognitoUserPool object: 

CognitoUserPool(context, AWSMobileClient.getInstance().configuration)

**Comment by Shubhraaaj** [comment]
This worked for me
`CognitoUserPool cognitoUserPool = new CognitoUserPool(getApplicationContext(),
                AWSMobileClient.getInstance().getConfiguration());
mAWSAppSyncClient = AWSAppSyncClient.builder()
                .context(getApplicationContext())
                .cognitoUserPoolsAuthProvider(new BasicCognitoUserPoolsAuthProvider(cognitoUserPool))
                .awsConfiguration(new AWSConfiguration(getApplicationContext()))
                .build();`

**Comment by Sergey-ssm** [comment]
by some reason got null pointer with `AWSMobileClient.getInstance().getConfiguration()`, but new `AWSConfiguration(getApplicationContext()) ` works fine
